INSERT INTO model (brand_id, name) VALUES (149,'CITY 50');
INSERT INTO model (brand_id, name) VALUES (149,'CITY 90');
INSERT INTO model (brand_id, name) VALUES (149,'DAKAR 30.0');
INSERT INTO model (brand_id, name) VALUES (149,'ELEFANT 16.5');
INSERT INTO model (brand_id, name) VALUES (149,'ELEFANT 27.5');
INSERT INTO model (brand_id, name) VALUES (149,'ELEFANTRÉ 16.5');
INSERT INTO model (brand_id, name) VALUES (149,'ELEFANTRÉ 16.5 ES');
INSERT INTO model (brand_id, name) VALUES (149,'ELEFANTRÉ 30.0');
INSERT INTO model (brand_id, name) VALUES (149,'ELEFANTRÉ 30.0 ES');
INSERT INTO model (brand_id, name) VALUES (149,'EX 27.5');
INSERT INTO model (brand_id, name) VALUES (149,'SST 13.5');
INSERT INTO model (brand_id, name) VALUES (149,'SUPER CITY 125');
INSERT INTO model (brand_id, name) VALUES (149,'SXT 16.5');
INSERT INTO model (brand_id, name) VALUES (149,'SXT 27.5 E');
INSERT INTO model (brand_id, name) VALUES (149,'SXT 27.5 EX');
INSERT INTO model (brand_id, name) VALUES (149,'TCHAU 50');

INSERT INTO model (brand_id, name) VALUES (150,'350');

INSERT INTO model (brand_id, name) VALUES (151,'AMAZONAS');
 
INSERT INTO model (brand_id, name) VALUES (152,'110 MIX');
INSERT INTO model (brand_id, name) VALUES (152,'110 X');
INSERT INTO model (brand_id, name) VALUES (152,'125 A');
INSERT INTO model (brand_id, name) VALUES (152,'125 S');
INSERT INTO model (brand_id, name) VALUES (152,'150 SC');
INSERT INTO model (brand_id, name) VALUES (152,'150 TC');
INSERT INTO model (brand_id, name) VALUES (152,'250 C1');
INSERT INTO model (brand_id, name) VALUES (152,'250 CROSS FX');
INSERT INTO model (brand_id, name) VALUES (152,'AMAZON 150');
INSERT INTO model (brand_id, name) VALUES (152,'BIG BOY 50');
INSERT INTO model (brand_id, name) VALUES (152,'COUGAR 150');
INSERT INTO model (brand_id, name) VALUES (152,'ENDURANCE 250 RX');
INSERT INTO model (brand_id, name) VALUES (152,'LX 125 / 26');
INSERT INTO model (brand_id, name) VALUES (152,'SELVA 250');
INSERT INTO model (brand_id, name) VALUES (152,'SNAKE 110');
INSERT INTO model (brand_id, name) VALUES (152,'THUNDER 300');

INSERT INTO model (brand_id, name) VALUES (153,'2009');
INSERT INTO model (brand_id, name) VALUES (153,'AREA-51');
INSERT INTO model (brand_id, name) VALUES (153,'CLASSIC');
INSERT INTO model (brand_id, name) VALUES (153,'DORSODURO 750');
INSERT INTO model (brand_id, name) VALUES (153,'LEONARDO');
INSERT INTO model (brand_id, name) VALUES (153,'MOTO');
INSERT INTO model (brand_id, name) VALUES (153,'PEGASO');
INSERT INTO model (brand_id, name) VALUES (153,'RALLY');
INSERT INTO model (brand_id, name) VALUES (153,'RS 125');
INSERT INTO model (brand_id, name) VALUES (153,'RS 250');
INSERT INTO model (brand_id, name) VALUES (153,'RS 50');
INSERT INTO model (brand_id, name) VALUES (153,'RSV 1000 R');
INSERT INTO model (brand_id, name) VALUES (153,'RSV MILLE');
INSERT INTO model (brand_id, name) VALUES (153,'RSV4 FACTORY');
INSERT INTO model (brand_id, name) VALUES (153,'RX 50');
INSERT INTO model (brand_id, name) VALUES (153,'SCARABEO 200');
INSERT INTO model (brand_id, name) VALUES (153,'SCARABEO 300');
INSERT INTO model (brand_id, name) VALUES (153,'SCARABEO 500');
INSERT INTO model (brand_id, name) VALUES (153,'SCARABEO BRIGTH');
INSERT INTO model (brand_id, name) VALUES (153,'SCARABEO CLASSIC');
INSERT INTO model (brand_id, name) VALUES (153,'SCARABEO DE LUXE');
INSERT INTO model (brand_id, name) VALUES (153,'SONIC');
INSERT INTO model (brand_id, name) VALUES (153,'SR RACING');
INSERT INTO model (brand_id, name) VALUES (153,'SR STEALTH');
INSERT INTO model (brand_id, name) VALUES (153,'SR WWW');

INSERT INTO model (brand_id, name) VALUES (154,'CLASSIC 150');

INSERT INTO model (brand_id, name) VALUES (155,'MIRAGE SPORT');

INSERT INTO model (brand_id, name) VALUES (156,'TNT 1130 CAFÉ RACER');
INSERT INTO model (brand_id, name) VALUES (156,'TNT 1130S');
INSERT INTO model (brand_id, name) VALUES (156,'TNT 899');
INSERT INTO model (brand_id, name) VALUES (156,'TNT 899S');
INSERT INTO model (brand_id, name) VALUES (156,'TRE 1130K');
INSERT INTO model (brand_id, name) VALUES (156,'TRE 1130K AMAZONAS');

INSERT INTO model (brand_id, name) VALUES (157,'DB5R');
INSERT INTO model (brand_id, name) VALUES (157,'DB6 DELIRIO');
INSERT INTO model (brand_id, name) VALUES (157,'DB6R DELIRIO');
INSERT INTO model (brand_id, name) VALUES (157,'DB7');

INSERT INTO model (brand_id, name) VALUES (158,'F 650');
INSERT INTO model (brand_id, name) VALUES (158,'F 650 CS');
INSERT INTO model (brand_id, name) VALUES (158,'F 650 GS');
INSERT INTO model (brand_id, name) VALUES (158,'F 650 GS DAKAR');
INSERT INTO model (brand_id, name) VALUES (158,'F 800 GS');
INSERT INTO model (brand_id, name) VALUES (158,'F 800 R');
INSERT INTO model (brand_id, name) VALUES (158,'F 800 S');
INSERT INTO model (brand_id, name) VALUES (158,'G 450 X');
INSERT INTO model (brand_id, name) VALUES (158,'G 650 GS');
INSERT INTO model (brand_id, name) VALUES (158,'G 650 XCHALLENGE');
INSERT INTO model (brand_id, name) VALUES (158,'G 650 XCOUNTRY');
INSERT INTO model (brand_id, name) VALUES (158,'G 650 XMOTO');
INSERT INTO model (brand_id, name) VALUES (158,'K 100');
INSERT INTO model (brand_id, name) VALUES (158,'K 100 RS');
INSERT INTO model (brand_id, name) VALUES (158,'K 1100 LT');
INSERT INTO model (brand_id, name) VALUES (158,'K 1100 RS');
INSERT INTO model (brand_id, name) VALUES (158,'K 1200 GT');
INSERT INTO model (brand_id, name) VALUES (158,'K 1200 LT');
INSERT INTO model (brand_id, name) VALUES (158,'K 1200 R');
INSERT INTO model (brand_id, name) VALUES (158,'K 1200 RS');
INSERT INTO model (brand_id, name) VALUES (158,'K 1200 S');
INSERT INTO model (brand_id, name) VALUES (158,'K 1300 GT');
INSERT INTO model (brand_id, name) VALUES (158,'K 1300 R');
INSERT INTO model (brand_id, name) VALUES (158,'K 1300 S');
INSERT INTO model (brand_id, name) VALUES (158,'K 1600 GT');
INSERT INTO model (brand_id, name) VALUES (158,'K 1600 GTL');
INSERT INTO model (brand_id, name) VALUES (158,'K 75');
INSERT INTO model (brand_id, name) VALUES (158,'R 100 RS');
INSERT INTO model (brand_id, name) VALUES (158,'R 1100 GS');
INSERT INTO model (brand_id, name) VALUES (158,'R 1100 GS 75');
INSERT INTO model (brand_id, name) VALUES (158,'R 1100 R');
INSERT INTO model (brand_id, name) VALUES (158,'R 1100 RS');
INSERT INTO model (brand_id, name) VALUES (158,'R 1100 RT');
INSERT INTO model (brand_id, name) VALUES (158,'R 1100 S');
INSERT INTO model (brand_id, name) VALUES (158,'R 1150 GS');
INSERT INTO model (brand_id, name) VALUES (158,'R 1150 GS ADVENTURE');
INSERT INTO model (brand_id, name) VALUES (158,'R 1150 R');
INSERT INTO model (brand_id, name) VALUES (158,'R 1150 R ROCKSTER');
INSERT INTO model (brand_id, name) VALUES (158,'R 1150 RS');
INSERT INTO model (brand_id, name) VALUES (158,'R 1150 RT');
INSERT INTO model (brand_id, name) VALUES (158,'R 1200 C');
INSERT INTO model (brand_id, name) VALUES (158,'R 1200 C AVANTGARD');
INSERT INTO model (brand_id, name) VALUES (158,'R 1200 C CLASSIC');
INSERT INTO model (brand_id, name) VALUES (158,'R 1200 C INDEPENDENT');
INSERT INTO model (brand_id, name) VALUES (158,'R 1200 CL');
INSERT INTO model (brand_id, name) VALUES (158,'R 1200 GS');
INSERT INTO model (brand_id, name) VALUES (158,'R 1200 GS ADVENTURE');
INSERT INTO model (brand_id, name) VALUES (158,'R 1200 GS HP2');
INSERT INTO model (brand_id, name) VALUES (158,'R 1200 RT');
INSERT INTO model (brand_id, name) VALUES (158,'R90S');
INSERT INTO model (brand_id, name) VALUES (158,'S 1000 RR');

INSERT INTO model (brand_id, name) VALUES (159,'ELEGANT 50');
INSERT INTO model (brand_id, name) VALUES (159,'FT 125 FOSTI');
INSERT INTO model (brand_id, name) VALUES (159,'JT 100 JAGUAR');
INSERT INTO model (brand_id, name) VALUES (159,'JT 50 JAGUAR');

INSERT INTO model (brand_id, name) VALUES (160,'CAN AM SPYDER ROADSTER');
INSERT INTO model (brand_id, name) VALUES (160,'DS 250');
INSERT INTO model (brand_id, name) VALUES (160,'DS 450');
INSERT INTO model (brand_id, name) VALUES (160,'DS 450 X');
INSERT INTO model (brand_id, name) VALUES (160,'DS 650');
INSERT INTO model (brand_id, name) VALUES (160,'DS 70');
INSERT INTO model (brand_id, name) VALUES (160,'DS 90');
INSERT INTO model (brand_id, name) VALUES (160,'DS 90 X');
INSERT INTO model (brand_id, name) VALUES (160,'OUTLANDER 400');
INSERT INTO model (brand_id, name) VALUES (160,'OUTLANDER 400 H.O. EFI');
INSERT INTO model (brand_id, name) VALUES (160,'OUTLANDER 400 H.O. EFI XT');
INSERT INTO model (brand_id, name) VALUES (160,'OUTLANDER 400 XT');
INSERT INTO model (brand_id, name) VALUES (160,'OUTLANDER 650');
INSERT INTO model (brand_id, name) VALUES (160,'OUTLANDER 650 XT');
INSERT INTO model (brand_id, name) VALUES (160,'OUTLANDER 800');
INSERT INTO model (brand_id, name) VALUES (160,'OUTLANDER 800 XT');
INSERT INTO model (brand_id, name) VALUES (160,'OUTLANDER MAX 400');
INSERT INTO model (brand_id, name) VALUES (160,'OUTLANDER MAX 400 H.O. EFI');
INSERT INTO model (brand_id, name) VALUES (160,'OUTLANDER MAX 400 H.O. EFI XT');
INSERT INTO model (brand_id, name) VALUES (160,'OUTLANDER MAX 400 XT');
INSERT INTO model (brand_id, name) VALUES (160,'OUTLANDER MAX 650');
INSERT INTO model (brand_id, name) VALUES (160,'OUTLANDER MAX 650 XT');
INSERT INTO model (brand_id, name) VALUES (160,'OUTLANDER MAX 800');
INSERT INTO model (brand_id, name) VALUES (160,'OUTLANDER MAX 800 LTD');
INSERT INTO model (brand_id, name) VALUES (160,'OUTLANDER MAX 800 XT');
INSERT INTO model (brand_id, name) VALUES (160,'RENEGADE 500 H.O. EFI');
INSERT INTO model (brand_id, name) VALUES (160,'RENEGADE 800 H.O. EFI');
INSERT INTO model (brand_id, name) VALUES (160,'RENEGADE 800 X');

INSERT INTO model (brand_id, name) VALUES (161,'1125CR');
INSERT INTO model (brand_id, name) VALUES (161,'1125R');
INSERT INTO model (brand_id, name) VALUES (161,'FIREBOLT XB12R');
INSERT INTO model (brand_id, name) VALUES (161,'LIGHTNING CITY CROSS XB9SX');
INSERT INTO model (brand_id, name) VALUES (161,'LIGHTNING XB12S');
INSERT INTO model (brand_id, name) VALUES (161,'LIGHTNING XB12SS');
INSERT INTO model (brand_id, name) VALUES (161,'LIGHTNING XB12STT');
INSERT INTO model (brand_id, name) VALUES (161,'LIGHTNING XB9SX');
INSERT INTO model (brand_id, name) VALUES (161,'ULYSSES XB12X');
INSERT INTO model (brand_id, name) VALUES (161,'ULYSSES XB12X TOURING');
INSERT INTO model (brand_id, name) VALUES (161,'ULYSSES XB12XP');
INSERT INTO model (brand_id, name) VALUES (161,'ULYSSES XB12XT');
INSERT INTO model (brand_id, name) VALUES (161,'ULYSSES XS 12X 1200');
 
INSERT INTO model (brand_id, name) VALUES (162,'1.6 STANDARD');
INSERT INTO model (brand_id, name) VALUES (162,'SPORT');
INSERT INTO model (brand_id, name) VALUES (162,'STAR I');
INSERT INTO model (brand_id, name) VALUES (162,'STAR II');
INSERT INTO model (brand_id, name) VALUES (162,'STAR II TOP');
INSERT INTO model (brand_id, name) VALUES (162,'TOP');

INSERT INTO model (brand_id, name) VALUES (163,'CANYON 500');
INSERT INTO model (brand_id, name) VALUES (163,'CANYON 600');
INSERT INTO model (brand_id, name) VALUES (163,'ELEFANT 750');
INSERT INTO model (brand_id, name) VALUES (163,'ELEFANT 900');
INSERT INTO model (brand_id, name) VALUES (163,'GRAND CANYON 900');
INSERT INTO model (brand_id, name) VALUES (163,'MITO 125');
INSERT INTO model (brand_id, name) VALUES (163,'NAVIGATOR 1000');
INSERT INTO model (brand_id, name) VALUES (163,'PLANET 125');
INSERT INTO model (brand_id, name) VALUES (163,'RAPTOR 125');
INSERT INTO model (brand_id, name) VALUES (163,'RAPTOR 650');
INSERT INTO model (brand_id, name) VALUES (163,'ROADSTER 200');
INSERT INTO model (brand_id, name) VALUES (163,'SUPER CITY 125');
INSERT INTO model (brand_id, name) VALUES (163,'V-RAPTOR 1000');
INSERT INTO model (brand_id, name) VALUES (163,'W-16 600');
INSERT INTO model (brand_id, name) VALUES (163,'XTRA-RAPTOR 1000');

INSERT INTO model (brand_id, name) VALUES (164,'MOBILETE 50');

INSERT INTO model (brand_id, name) VALUES (165,'PHOENIX 200');

INSERT INTO model (brand_id, name) VALUES (166,'ALTINO 100');
INSERT INTO model (brand_id, name) VALUES (166,'MESSAGE 50');
INSERT INTO model (brand_id, name) VALUES (166,'VC 125 ADVANCED');
INSERT INTO model (brand_id, name) VALUES (166,'VF 125');
INSERT INTO model (brand_id, name) VALUES (166,'VL 125 DAYSTAR');
INSERT INTO model (brand_id, name) VALUES (166,'VS 125');
INSERT INTO model (brand_id, name) VALUES (166,'VT 125 MAGMA');

INSERT INTO model (brand_id, name) VALUES (167,'APACHE RTR 150');
INSERT INTO model (brand_id, name) VALUES (167,'CITYCOM 300 I');
INSERT INTO model (brand_id, name) VALUES (167,'KANSAS 150');
INSERT INTO model (brand_id, name) VALUES (167,'KANSAS 250');
INSERT INTO model (brand_id, name) VALUES (167,'LASER 150');
INSERT INTO model (brand_id, name) VALUES (167,'SMART 125');
INSERT INTO model (brand_id, name) VALUES (167,'SPEED 150');
INSERT INTO model (brand_id, name) VALUES (167,'SPEED 150 CARGO');
INSERT INTO model (brand_id, name) VALUES (167,'SUPER 100');
INSERT INTO model (brand_id, name) VALUES (167,'SUPER 50');
INSERT INTO model (brand_id, name) VALUES (167,'ZIG 100+');
INSERT INTO model (brand_id, name) VALUES (167,'ZIG 110');

INSERT INTO model (brand_id, name) VALUES (168,'DY 110-6');
INSERT INTO model (brand_id, name) VALUES (168,'DY 125-8');
INSERT INTO model (brand_id, name) VALUES (168,'DY 125T-10');
INSERT INTO model (brand_id, name) VALUES (168,'DY 150-7');
INSERT INTO model (brand_id, name) VALUES (168,'DY 150-9');
INSERT INTO model (brand_id, name) VALUES (168,'DY 150GY');
INSERT INTO model (brand_id, name) VALUES (168,'DY 150ZH');
INSERT INTO model (brand_id, name) VALUES (168,'DY 250-2');
 
INSERT INTO model (brand_id, name) VALUES (169,'ATLANTIS');
INSERT INTO model (brand_id, name) VALUES (169,'GPR 50R');
INSERT INTO model (brand_id, name) VALUES (169,'PREDADOR AR');
INSERT INTO model (brand_id, name) VALUES (169,'PREDATOR LC');
INSERT INTO model (brand_id, name) VALUES (169,'SENDA 125R');

INSERT INTO model (brand_id, name) VALUES (170,'749');
INSERT INTO model (brand_id, name) VALUES (170,'848');
INSERT INTO model (brand_id, name) VALUES (170,'916');
INSERT INTO model (brand_id, name) VALUES (170,'996');
INSERT INTO model (brand_id, name) VALUES (170,'996 S');
INSERT INTO model (brand_id, name) VALUES (170,'998');
INSERT INTO model (brand_id, name) VALUES (170,'999');
INSERT INTO model (brand_id, name) VALUES (170,'999 R XEROX');
INSERT INTO model (brand_id, name) VALUES (170,'D16 RR');
INSERT INTO model (brand_id, name) VALUES (170,'DIAVEL 1198');
INSERT INTO model (brand_id, name) VALUES (170,'DIAVEL 1198 CARBON');
INSERT INTO model (brand_id, name) VALUES (170,'HIPERMOTARD 1100 EVO');
INSERT INTO model (brand_id, name) VALUES (170,'HYPERMOTARD 1100');
INSERT INTO model (brand_id, name) VALUES (170,'HYPERMOTARD 796');
INSERT INTO model (brand_id, name) VALUES (170,'MONSTER 1100');
INSERT INTO model (brand_id, name) VALUES (170,'MONSTER 1100S');
INSERT INTO model (brand_id, name) VALUES (170,'MONSTER 600');
INSERT INTO model (brand_id, name) VALUES (170,'MONSTER 620');
INSERT INTO model (brand_id, name) VALUES (170,'MONSTER 695');
INSERT INTO model (brand_id, name) VALUES (170,'MONSTER 696');
INSERT INTO model (brand_id, name) VALUES (170,'MONSTER 900');
INSERT INTO model (brand_id, name) VALUES (170,'MONSTER S2-R 1000');
INSERT INTO model (brand_id, name) VALUES (170,'MONSTER S4 916');
INSERT INTO model (brand_id, name) VALUES (170,'MONSTER S4 R 996');
INSERT INTO model (brand_id, name) VALUES (170,'MONSTER S4 RS TESTASTRETTA');
INSERT INTO model (brand_id, name) VALUES (170,'MULTISTRADA 1000');
INSERT INTO model (brand_id, name) VALUES (170,'MULTISTRADA 1100');
INSERT INTO model (brand_id, name) VALUES (170,'MULTISTRADA 1200');
INSERT INTO model (brand_id, name) VALUES (170,'MULTISTRADA 1200S');
INSERT INTO model (brand_id, name) VALUES (170,'MULTISTRADA 1200S TOURING');
INSERT INTO model (brand_id, name) VALUES (170,'MULTISTRADA 620');
INSERT INTO model (brand_id, name) VALUES (170,'SPORT CLASSIC 1000');
INSERT INTO model (brand_id, name) VALUES (170,'SPORTCLASSIC PAUL SMART 1000-LE');
INSERT INTO model (brand_id, name) VALUES (170,'SS 900');
INSERT INTO model (brand_id, name) VALUES (170,'ST 2 900');
INSERT INTO model (brand_id, name) VALUES (170,'ST 4 900');
INSERT INTO model (brand_id, name) VALUES (170,'STONER');
INSERT INTO model (brand_id, name) VALUES (170,'STREETFIGHTER');
INSERT INTO model (brand_id, name) VALUES (170,'STREETFIGHTER S');
INSERT INTO model (brand_id, name) VALUES (170,'SUPERBIKE 1098');
INSERT INTO model (brand_id, name) VALUES (170,'SUPERBIKE 1098S');
INSERT INTO model (brand_id, name) VALUES (170,'SUPERBIKE 1198 ');
INSERT INTO model (brand_id, name) VALUES (170,'SUPERBIKE 1198 S');
INSERT INTO model (brand_id, name) VALUES (170,'SUPERBIKE 848');

INSERT INTO model (brand_id, name) VALUES (171,'MIRAGE');
INSERT INTO model (brand_id, name) VALUES (171,'ONE');
INSERT INTO model (brand_id, name) VALUES (171,'ONE RACING');

INSERT INTO model (brand_id, name) VALUES (172,'150 ADVENTURE');
INSERT INTO model (brand_id, name) VALUES (172,'250 ELITE');
INSERT INTO model (brand_id, name) VALUES (172,'49 AIR');
 
INSERT INTO model (brand_id, name) VALUES (173,'FY 100-10A');
INSERT INTO model (brand_id, name) VALUES (173,'FY 125-19');
INSERT INTO model (brand_id, name) VALUES (173,'FY 125-20 SACHS');
INSERT INTO model (brand_id, name) VALUES (173,'FY 125EY-2');
INSERT INTO model (brand_id, name) VALUES (173,'FY 125Y-3');
INSERT INTO model (brand_id, name) VALUES (173,'FY 150-3');
INSERT INTO model (brand_id, name) VALUES (173,'FY 150T-18');
INSERT INTO model (brand_id, name) VALUES (173,'FY 250');
 
INSERT INTO model (brand_id, name) VALUES (174,'GR 08T4');
INSERT INTO model (brand_id, name) VALUES (174,'GR 125S');
INSERT INTO model (brand_id, name) VALUES (174,'GR 125ST');
INSERT INTO model (brand_id, name) VALUES (174,'GR 125T3');
INSERT INTO model (brand_id, name) VALUES (174,'GR 125T3 TINA');
INSERT INTO model (brand_id, name) VALUES (174,'GR 125U');
INSERT INTO model (brand_id, name) VALUES (174,'GR 125Z');
INSERT INTO model (brand_id, name) VALUES (174,'GR 150P');
INSERT INTO model (brand_id, name) VALUES (174,'GR 150ST');
INSERT INTO model (brand_id, name) VALUES (174,'GR 150T3');
INSERT INTO model (brand_id, name) VALUES (174,'GR 150TI');
INSERT INTO model (brand_id, name) VALUES (174,'GR 150U');
INSERT INTO model (brand_id, name) VALUES (174,'GR 250T3');
INSERT INTO model (brand_id, name) VALUES (174,'GR 250V');
INSERT INTO model (brand_id, name) VALUES (174,'GR 500ATV');
 
INSERT INTO model (brand_id, name) VALUES (175,'EC 125');
INSERT INTO model (brand_id, name) VALUES (175,'EC 200');
INSERT INTO model (brand_id, name) VALUES (175,'EC 200 HOBBY');
INSERT INTO model (brand_id, name) VALUES (175,'EC 250');
INSERT INTO model (brand_id, name) VALUES (175,'EC 250 F');
INSERT INTO model (brand_id, name) VALUES (175,'EC 300');
INSERT INTO model (brand_id, name) VALUES (175,'EC 400 FSE');
INSERT INTO model (brand_id, name) VALUES (175,'EC 450');
INSERT INTO model (brand_id, name) VALUES (175,'EC 50 ROOKIE');
INSERT INTO model (brand_id, name) VALUES (175,'FSE 450');
INSERT INTO model (brand_id, name) VALUES (175,'FSR 450');
INSERT INTO model (brand_id, name) VALUES (175,'MC 125');
INSERT INTO model (brand_id, name) VALUES (175,'MC 250');
INSERT INTO model (brand_id, name) VALUES (175,'PAMPERA 125');
INSERT INTO model (brand_id, name) VALUES (175,'PAMPERA 250');
INSERT INTO model (brand_id, name) VALUES (175,'PAMPERA 450');
INSERT INTO model (brand_id, name) VALUES (175,'SM 125');
INSERT INTO model (brand_id, name) VALUES (175,'SM 250');
INSERT INTO model (brand_id, name) VALUES (175,'SM 450');
INSERT INTO model (brand_id, name) VALUES (175,'SM 450 FSE');
INSERT INTO model (brand_id, name) VALUES (175,'SM 50');
INSERT INTO model (brand_id, name) VALUES (175,'TX BOY 50');
INSERT INTO model (brand_id, name) VALUES (175,'TXT 125 PRO');
INSERT INTO model (brand_id, name) VALUES (175,'TXT 200 Contact');
INSERT INTO model (brand_id, name) VALUES (175,'TXT 280');
INSERT INTO model (brand_id, name) VALUES (175,'TXT 280 Contact');
INSERT INTO model (brand_id, name) VALUES (175,'TXT 280 PRO');
INSERT INTO model (brand_id, name) VALUES (175,'TXT 321 Contact');
INSERT INTO model (brand_id, name) VALUES (175,'TXT 50 ROOKIE');
INSERT INTO model (brand_id, name) VALUES (175,'TXT BOY 50');
INSERT INTO model (brand_id, name) VALUES (175,'TXT PRO 250');
INSERT INTO model (brand_id, name) VALUES (175,'TXT PRO 300');

INSERT INTO model (brand_id, name) VALUES (176,'NEXUS 500');
 
INSERT INTO model (brand_id, name) VALUES (177,'EASY 110');
INSERT INTO model (brand_id, name) VALUES (177,'RUNNER 125');
INSERT INTO model (brand_id, name) VALUES (177,'SAFARI 150');
INSERT INTO model (brand_id, name) VALUES (177,'SPORT 150');
 
INSERT INTO model (brand_id, name) VALUES (178,'STELVIO 1200 ABS');
 
INSERT INTO model (brand_id, name) VALUES (179,'HB 110-3');
INSERT INTO model (brand_id, name) VALUES (179,'HB 125-9');
INSERT INTO model (brand_id, name) VALUES (179,'HB 150');
INSERT INTO model (brand_id, name) VALUES (179,'HB 150T');
INSERT INTO model (brand_id, name) VALUES (179,'HB 50Q');
 
INSERT INTO model (brand_id, name) VALUES (180,'DYNA CONVERTIBLE');
INSERT INTO model (brand_id, name) VALUES (180,'DYNA LOW RIDER');
INSERT INTO model (brand_id, name) VALUES (180,'DYNA LOW RIDER CONVERTIBLE');
INSERT INTO model (brand_id, name) VALUES (180,'DYNA SUPER GLIDE');
INSERT INTO model (brand_id, name) VALUES (180,'DYNA SUPER GLIDE CUSTOM');
INSERT INTO model (brand_id, name) VALUES (180,'DYNA WIDE GLIDE');
INSERT INTO model (brand_id, name) VALUES (180,'EG ROAD KING FUEL INJECTION');
INSERT INTO model (brand_id, name) VALUES (180,'ELECTRA GLIDE SCREAMIN EAGLE');
INSERT INTO model (brand_id, name) VALUES (180,'ELECTRA GLIDE CLASSIC');
INSERT INTO model (brand_id, name) VALUES (180,'ELECTRA GLIDE SPECIAL');
INSERT INTO model (brand_id, name) VALUES (180,'ELECTRA GLIDE STANDARD');
INSERT INTO model (brand_id, name) VALUES (180,'ELECTRA GLIDE ULTRA FUEL INJECTION');
INSERT INTO model (brand_id, name) VALUES (180,'FAT BOY SCREAMIN EAGLE');
INSERT INTO model (brand_id, name) VALUES (180,'FLSTF FB');
INSERT INTO model (brand_id, name) VALUES (180,'FX');
INSERT INTO model (brand_id, name) VALUES (180,'HERITAGE SOFTAIL CLASSIC');
INSERT INTO model (brand_id, name) VALUES (180,'HERITAGE SOFTAIL CUSTOM');
INSERT INTO model (brand_id, name) VALUES (180,'HERITAGE SOFTAIL SPRINGER');
INSERT INTO model (brand_id, name) VALUES (180,'NIGHT ROD SPECIAL');
INSERT INTO model (brand_id, name) VALUES (180,'NIGHT TRAIN');
INSERT INTO model (brand_id, name) VALUES (180,'ROAD KING');
INSERT INTO model (brand_id, name) VALUES (180,'ROAD KING CLASSIC');
INSERT INTO model (brand_id, name) VALUES (180,'ROAD KING CUSTOM');
INSERT INTO model (brand_id, name) VALUES (180,'ROAD KING POLICE FLHP');
INSERT INTO model (brand_id, name) VALUES (180,'ROAD KING SCREAMIN EAGLE');
INSERT INTO model (brand_id, name) VALUES (180,'ROCKER C');
INSERT INTO model (brand_id, name) VALUES (180,'SCREAMING EAGLE SOFTAIL SPRINGER');
INSERT INTO model (brand_id, name) VALUES (180,'SHOVELHEAD');
INSERT INTO model (brand_id, name) VALUES (180,'SOFTAIL CLASSIC');
INSERT INTO model (brand_id, name) VALUES (180,'SOFTAIL COVERTIBLE');
INSERT INTO model (brand_id, name) VALUES (180,'SOFTAIL CUSTOM');
INSERT INTO model (brand_id, name) VALUES (180,'SOFTAIL DELUXE');
INSERT INTO model (brand_id, name) VALUES (180,'SOFTAIL DEUCE');
INSERT INTO model (brand_id, name) VALUES (180,'SOFTAIL FAT BOY');
INSERT INTO model (brand_id, name) VALUES (180,'SOFTAIL FAT BOY SPECIAL');
INSERT INTO model (brand_id, name) VALUES (180,'SOFTAIL HERITAGE CUSTOM');
INSERT INTO model (brand_id, name) VALUES (180,'SOFTAIL ROCKER');
INSERT INTO model (brand_id, name) VALUES (180,'SOFTAIL SPECIAL');
INSERT INTO model (brand_id, name) VALUES (180,'SOFTAIL SPRINGER');
INSERT INTO model (brand_id, name) VALUES (180,'SOFTAIL STANDARD');
INSERT INTO model (brand_id, name) VALUES (180,'SPORTSTER 1200 XL CUSTOM');
INSERT INTO model (brand_id, name) VALUES (180,'SPORTSTER 1200 XL CUSTOM C');
INSERT INTO model (brand_id, name) VALUES (180,'SPORTSTER 1200 XL SPORT');
INSERT INTO model (brand_id, name) VALUES (180,'SPORTSTER 1200 XL STANDARD');
INSERT INTO model (brand_id, name) VALUES (180,'SPORTSTER 1200 XLH');
INSERT INTO model (brand_id, name) VALUES (180,'SPORTSTER 883 LOW');
INSERT INTO model (brand_id, name) VALUES (180,'SPORTSTER 883 XL STANDARD');
INSERT INTO model (brand_id, name) VALUES (180,'SPORTSTER 883 XLH HUGGER');
INSERT INTO model (brand_id, name) VALUES (180,'SPORTSTER XL 1200 N');
INSERT INTO model (brand_id, name) VALUES (180,'SPORTSTER XL 883');
INSERT INTO model (brand_id, name) VALUES (180,'SPORTSTER XL 883 CUSTOM');
INSERT INTO model (brand_id, name) VALUES (180,'SPORTSTER XL 883 R ');
INSERT INTO model (brand_id, name) VALUES (180,'SPORTSTER XL 883N IRON');
INSERT INTO model (brand_id, name) VALUES (180,'SPOTSTER 883 ROADSTER');
INSERT INTO model (brand_id, name) VALUES (180,'SPOTSTER IRON 883');
INSERT INTO model (brand_id, name) VALUES (180,'SPRINGER SCREAMIN EAGLE');
INSERT INTO model (brand_id, name) VALUES (180,'STREET GLIDE');
INSERT INTO model (brand_id, name) VALUES (180,'STREET ROD');
INSERT INTO model (brand_id, name) VALUES (180,'U FLAT HEAD');
INSERT INTO model (brand_id, name) VALUES (180,'ULTRA ELECTRA GLIDE CLASSIC');
INSERT INTO model (brand_id, name) VALUES (180,'V-ROD');
INSERT INTO model (brand_id, name) VALUES (180,'V-ROD MUSCLE');
INSERT INTO model (brand_id, name) VALUES (180,'V-ROD SCREAMIN EAGLE');
INSERT INTO model (brand_id, name) VALUES (180,'V-ROD SPORT');
INSERT INTO model (brand_id, name) VALUES (180,'V-ROD X');
INSERT INTO model (brand_id, name) VALUES (180,'XR 1200');
INSERT INTO model (brand_id, name) VALUES (180,'XR 1200 X');

INSERT INTO model (brand_id, name) VALUES (181,'LEGION 125');
 
INSERT INTO model (brand_id, name) VALUES (182,'1200 GOLD WING');
INSERT INTO model (brand_id, name) VALUES (182,'125');
INSERT INTO model (brand_id, name) VALUES (182,'1500 GOLD WING');
INSERT INTO model (brand_id, name) VALUES (182,'750 MAGNA');
INSERT INTO model (brand_id, name) VALUES (182,'BIZ 125 +');
INSERT INTO model (brand_id, name) VALUES (182,'BIZ 125 ES');
INSERT INTO model (brand_id, name) VALUES (182,'BIZ 125 EX');
INSERT INTO model (brand_id, name) VALUES (182,'BIZ 125 KS');
INSERT INTO model (brand_id, name) VALUES (182,'C 100 BIZ');
INSERT INTO model (brand_id, name) VALUES (182,'C 100 BIZ ES');
INSERT INTO model (brand_id, name) VALUES (182,'C 100 BIZ+');
INSERT INTO model (brand_id, name) VALUES (182,'C 100 DREAM');
INSERT INTO model (brand_id, name) VALUES (182,'CB 1000 - BIG ONE');
INSERT INTO model (brand_id, name) VALUES (182,'CB 1000R');
INSERT INTO model (brand_id, name) VALUES (182,'CB 1300 SUPER FOUR');
INSERT INTO model (brand_id, name) VALUES (182,'CB 300R');
INSERT INTO model (brand_id, name) VALUES (182,'CB 350K');
INSERT INTO model (brand_id, name) VALUES (182,'CB 360');
INSERT INTO model (brand_id, name) VALUES (182,'CB 400');
INSERT INTO model (brand_id, name) VALUES (182,'CB 400 FOUR');
INSERT INTO model (brand_id, name) VALUES (182,'CB 400 II');
INSERT INTO model (brand_id, name) VALUES (182,'CB 450');
INSERT INTO model (brand_id, name) VALUES (182,'CB 450 DX');
INSERT INTO model (brand_id, name) VALUES (182,'CB 50');
INSERT INTO model (brand_id, name) VALUES (182,'CB 500');
INSERT INTO model (brand_id, name) VALUES (182,'CB 500 FOUR');
INSERT INTO model (brand_id, name) VALUES (182,'CB 550 FOUR');
INSERT INTO model (brand_id, name) VALUES (182,'CB 600F HORNET');
INSERT INTO model (brand_id, name) VALUES (182,'CB 750 FOUR');
INSERT INTO model (brand_id, name) VALUES (182,'CB 750 KZ');
INSERT INTO model (brand_id, name) VALUES (182,'CB 900F BOLD´OR');
INSERT INTO model (brand_id, name) VALUES (182,'CB 900F HORNET');
INSERT INTO model (brand_id, name) VALUES (182,'CBF 125');
INSERT INTO model (brand_id, name) VALUES (182,'CBR 1000F');
INSERT INTO model (brand_id, name) VALUES (182,'CBR 1000RR FIREBLADE');
INSERT INTO model (brand_id, name) VALUES (182,'CBR 1000RR REPSOL');
INSERT INTO model (brand_id, name) VALUES (182,'CBR 1100XX SUPER BLACKBIRD');
INSERT INTO model (brand_id, name) VALUES (182,'CBR 125R');
INSERT INTO model (brand_id, name) VALUES (182,'CBR 450');
INSERT INTO model (brand_id, name) VALUES (182,'CBR 450 SR');
INSERT INTO model (brand_id, name) VALUES (182,'CBR 600F');
INSERT INTO model (brand_id, name) VALUES (182,'CBR 600RR');
INSERT INTO model (brand_id, name) VALUES (182,'CBR 900RR');
INSERT INTO model (brand_id, name) VALUES (182,'CBR 900RR FIREBLADE');
INSERT INTO model (brand_id, name) VALUES (182,'CBR 929RR');
INSERT INTO model (brand_id, name) VALUES (182,'CBR 954RR FIREBLADE');
INSERT INTO model (brand_id, name) VALUES (182,'CBX 1050');
INSERT INTO model (brand_id, name) VALUES (182,'CBX 150 AERO');
INSERT INTO model (brand_id, name) VALUES (182,'CBX 200 STRADA');
INSERT INTO model (brand_id, name) VALUES (182,'CBX 250 TWISTER');
INSERT INTO model (brand_id, name) VALUES (182,'CBX 750 FOUR');
INSERT INTO model (brand_id, name) VALUES (182,'CBX 750 FOUR INDY');
INSERT INTO model (brand_id, name) VALUES (182,'CBX 750R');
INSERT INTO model (brand_id, name) VALUES (182,'CG 125');
INSERT INTO model (brand_id, name) VALUES (182,'CG 125 CARGO');
INSERT INTO model (brand_id, name) VALUES (182,'CG 125 CARGO ES');
INSERT INTO model (brand_id, name) VALUES (182,'CG 125 CARGO KS');
INSERT INTO model (brand_id, name) VALUES (182,'CG 125 ES FAN');
INSERT INTO model (brand_id, name) VALUES (182,'CG 125 FAN');
INSERT INTO model (brand_id, name) VALUES (182,'CG 125 KS FAN');
INSERT INTO model (brand_id, name) VALUES (182,'CG 125 ML');
INSERT INTO model (brand_id, name) VALUES (182,'CG 125 TITAN');
INSERT INTO model (brand_id, name) VALUES (182,'CG 125 TITAN ES');
INSERT INTO model (brand_id, name) VALUES (182,'CG 125 TITAN KS');
INSERT INTO model (brand_id, name) VALUES (182,'CG 125 TITAN KSE');
INSERT INTO model (brand_id, name) VALUES (182,'CG 125 TODAY');
INSERT INTO model (brand_id, name) VALUES (182,'CG 150 FAN ESDI');
INSERT INTO model (brand_id, name) VALUES (182,'CG 150 FAN ESI');
INSERT INTO model (brand_id, name) VALUES (182,'CG 150 JOB');
INSERT INTO model (brand_id, name) VALUES (182,'CG 150 SPORT');
INSERT INTO model (brand_id, name) VALUES (182,'CG 150 TITAN EDIÇÃO ESPECIAL');
INSERT INTO model (brand_id, name) VALUES (182,'CG 150 TITAN ES');
INSERT INTO model (brand_id, name) VALUES (182,'CG 150 TITAN ESD');
INSERT INTO model (brand_id, name) VALUES (182,'CG 150 TITAN KS');
INSERT INTO model (brand_id, name) VALUES (182,'CG 150 TITAN MIX ES');
INSERT INTO model (brand_id, name) VALUES (182,'CG 150 TITAN MIX ESD');
INSERT INTO model (brand_id, name) VALUES (182,'CG 150 TITAN MIX EX');
INSERT INTO model (brand_id, name) VALUES (182,'CG 150 TITAN MIX KS');
INSERT INTO model (brand_id, name) VALUES (182,'CH 125R SPACY');
INSERT INTO model (brand_id, name) VALUES (182,'CR 125');
INSERT INTO model (brand_id, name) VALUES (182,'CR 250');
INSERT INTO model (brand_id, name) VALUES (182,'CR 80');
INSERT INTO model (brand_id, name) VALUES (182,'CRF 150R');
INSERT INTO model (brand_id, name) VALUES (182,'CRF 230F');
INSERT INTO model (brand_id, name) VALUES (182,'CRF 250R');
INSERT INTO model (brand_id, name) VALUES (182,'CRF 250X');
INSERT INTO model (brand_id, name) VALUES (182,'CRF 450R');
INSERT INTO model (brand_id, name) VALUES (182,'CRF 450X');
INSERT INTO model (brand_id, name) VALUES (182,'CRF 50F');
INSERT INTO model (brand_id, name) VALUES (182,'GL 1000 GOLD WING');
INSERT INTO model (brand_id, name) VALUES (182,'GL 1500CF VALKYRIE INTERSTATE');
INSERT INTO model (brand_id, name) VALUES (182,'GL 1800 GOLD WING');
INSERT INTO model (brand_id, name) VALUES (182,'HELIX 250');
INSERT INTO model (brand_id, name) VALUES (182,'INTERCEPTOR V-FOUR');
INSERT INTO model (brand_id, name) VALUES (182,'LEAD 110');
INSERT INTO model (brand_id, name) VALUES (182,'LEAD 110 ES');
INSERT INTO model (brand_id, name) VALUES (182,'NX 150');
INSERT INTO model (brand_id, name) VALUES (182,'NX 200');
INSERT INTO model (brand_id, name) VALUES (182,'NX 350 SAHARA');
INSERT INTO model (brand_id, name) VALUES (182,'NX 650 DOMINATOR');
INSERT INTO model (brand_id, name) VALUES (182,'NX4 FALCON');
INSERT INTO model (brand_id, name) VALUES (182,'NXR 125 BROS ES');
INSERT INTO model (brand_id, name) VALUES (182,'NXR 125 BROS KS');
INSERT INTO model (brand_id, name) VALUES (182,'NXR 150 BROS ES');
INSERT INTO model (brand_id, name) VALUES (182,'NXR 150 BROS ESD');
INSERT INTO model (brand_id, name) VALUES (182,'NXR 150 BROS KS');
INSERT INTO model (brand_id, name) VALUES (182,'NXR 150 BROS MIX ES');
INSERT INTO model (brand_id, name) VALUES (182,'NXR 150 BROS MIX ESD');
INSERT INTO model (brand_id, name) VALUES (182,'NXR 150 BROS MIX KS');
INSERT INTO model (brand_id, name) VALUES (182,'POP 100');
INSERT INTO model (brand_id, name) VALUES (182,'SHADOW 1100 AC');
INSERT INTO model (brand_id, name) VALUES (182,'SHADOW 1100 OURO');
INSERT INTO model (brand_id, name) VALUES (182,'SHADOW 1100 VT');
INSERT INTO model (brand_id, name) VALUES (182,'SHADOW 600C VT');
INSERT INTO model (brand_id, name) VALUES (182,'SHADOW 750');
INSERT INTO model (brand_id, name) VALUES (182,'SHADOW 750 AM');
INSERT INTO model (brand_id, name) VALUES (182,'ST 1100 PAN EUROPEAN');
INSERT INTO model (brand_id, name) VALUES (182,'SUPER HAWK 1000');
INSERT INTO model (brand_id, name) VALUES (182,'TRX 350 FOURTRAX 4X2');
INSERT INTO model (brand_id, name) VALUES (182,'TRX 350 FOURTRAX 4X4');
INSERT INTO model (brand_id, name) VALUES (182,'TRX 350 FOURTRAX FM 4X4');
INSERT INTO model (brand_id, name) VALUES (182,'TRX 420 FOURTRAX 4X2');
INSERT INTO model (brand_id, name) VALUES (182,'TRX 420 FOURTRAX 4X4');
INSERT INTO model (brand_id, name) VALUES (182,'VALKYRIE 1500');
INSERT INTO model (brand_id, name) VALUES (182,'VALKYRIE 1800');
INSERT INTO model (brand_id, name) VALUES (182,'VF750F INTERCEPTOR');
INSERT INTO model (brand_id, name) VALUES (182,'VFR 1200F');
INSERT INTO model (brand_id, name) VALUES (182,'VT 1300 CR');
INSERT INTO model (brand_id, name) VALUES (182,'VT 1300 CS');
INSERT INTO model (brand_id, name) VALUES (182,'VT 1300 CX');
INSERT INTO model (brand_id, name) VALUES (182,'VTR 250');
INSERT INTO model (brand_id, name) VALUES (182,'VTX 1800C');
INSERT INTO model (brand_id, name) VALUES (182,'XL 1000V VARADERO');
INSERT INTO model (brand_id, name) VALUES (182,'XL 125 DUTY');
INSERT INTO model (brand_id, name) VALUES (182,'XL 125 VAREDERO');
INSERT INTO model (brand_id, name) VALUES (182,'XL 125S');
INSERT INTO model (brand_id, name) VALUES (182,'XL 250R');
INSERT INTO model (brand_id, name) VALUES (182,'XL 600V TRANSALP');
INSERT INTO model (brand_id, name) VALUES (182,'XL 700V TRANSALP');
INSERT INTO model (brand_id, name) VALUES (182,'XLR 125');
INSERT INTO model (brand_id, name) VALUES (182,'XLR 125 ES');
INSERT INTO model (brand_id, name) VALUES (182,'XLX 250R');
INSERT INTO model (brand_id, name) VALUES (182,'XLX 350R');
INSERT INTO model (brand_id, name) VALUES (182,'XR 200R');
INSERT INTO model (brand_id, name) VALUES (182,'XR 250 TORNADO');
INSERT INTO model (brand_id, name) VALUES (182,'XR 250R');
INSERT INTO model (brand_id, name) VALUES (182,'XR 400R');
INSERT INTO model (brand_id, name) VALUES (182,'XR 650');
INSERT INTO model (brand_id, name) VALUES (182,'XR 650L');
INSERT INTO model (brand_id, name) VALUES (182,'XRE 300');
INSERT INTO model (brand_id, name) VALUES (182,'XRV 750 AFRICA TWIN');
 
INSERT INTO model (brand_id, name) VALUES (183,'FE 400');
INSERT INTO model (brand_id, name) VALUES (183,'FE 501');
INSERT INTO model (brand_id, name) VALUES (183,'FE 550E');
 
INSERT INTO model (brand_id, name) VALUES (184,'510 CONTINENTAL');
INSERT INTO model (brand_id, name) VALUES (184,'CR 125');
INSERT INTO model (brand_id, name) VALUES (184,'CR 250');
INSERT INTO model (brand_id, name) VALUES (184,'HUSQY BOY J');
INSERT INTO model (brand_id, name) VALUES (184,'HUSQY BOY R');
INSERT INTO model (brand_id, name) VALUES (184,'HUSQY BOY S');
INSERT INTO model (brand_id, name) VALUES (184,'SM 125S');
INSERT INTO model (brand_id, name) VALUES (184,'SM 450R');
INSERT INTO model (brand_id, name) VALUES (184,'SM 450RR');
INSERT INTO model (brand_id, name) VALUES (184,'SM 510R');
INSERT INTO model (brand_id, name) VALUES (184,'SM 610');
INSERT INTO model (brand_id, name) VALUES (184,'SM 610S');
INSERT INTO model (brand_id, name) VALUES (184,'SMR 570R');
INSERT INTO model (brand_id, name) VALUES (184,'SMR 630');
INSERT INTO model (brand_id, name) VALUES (184,'TC 250');
INSERT INTO model (brand_id, name) VALUES (184,'TC 450');
INSERT INTO model (brand_id, name) VALUES (184,'TC 510');
INSERT INTO model (brand_id, name) VALUES (184,'TC 570');
INSERT INTO model (brand_id, name) VALUES (184,'TE 250');
INSERT INTO model (brand_id, name) VALUES (184,'TE 400');
INSERT INTO model (brand_id, name) VALUES (184,'TE 410');
INSERT INTO model (brand_id, name) VALUES (184,'TE 410E');
INSERT INTO model (brand_id, name) VALUES (184,'TE 450');
INSERT INTO model (brand_id, name) VALUES (184,'TE 510');
INSERT INTO model (brand_id, name) VALUES (184,'TE 570');
INSERT INTO model (brand_id, name) VALUES (184,'TE 610');
INSERT INTO model (brand_id, name) VALUES (184,'TE 610E');
INSERT INTO model (brand_id, name) VALUES (184,'WR 125');
INSERT INTO model (brand_id, name) VALUES (184,'WR 125 CUP');
INSERT INTO model (brand_id, name) VALUES (184,'WR 250');
INSERT INTO model (brand_id, name) VALUES (184,'WR 360');
INSERT INTO model (brand_id, name) VALUES (184,'WRE 125');
 
INSERT INTO model (brand_id, name) VALUES (185,'ACTION 100 ES');
INSERT INTO model (brand_id, name) VALUES (185,'ACTION 100 ESA');
INSERT INTO model (brand_id, name) VALUES (185,'BRAVE 150');
INSERT INTO model (brand_id, name) VALUES (185,'BRAVE 450R');
INSERT INTO model (brand_id, name) VALUES (185,'BRAVE 70');
INSERT INTO model (brand_id, name) VALUES (185,'MATRIX 150');
INSERT INTO model (brand_id, name) VALUES (185,'MOVING 125 ES');
INSERT INTO model (brand_id, name) VALUES (185,'MOVING 125 ESD');
INSERT INTO model (brand_id, name) VALUES (185,'ONE 125 ES');
INSERT INTO model (brand_id, name) VALUES (185,'ONE 125 ESD');
INSERT INTO model (brand_id, name) VALUES (185,'ONE 125 EX');
INSERT INTO model (brand_id, name) VALUES (185,'VINTAGE 150');
INSERT INTO model (brand_id, name) VALUES (185,'WARRIOR 250');
INSERT INTO model (brand_id, name) VALUES (185,'WARRIOR 400 4x4');
INSERT INTO model (brand_id, name) VALUES (185,'WARRIOR 700 4x4');
 
INSERT INTO model (brand_id, name) VALUES (186,'350 CHOPPER');
 
INSERT INTO model (brand_id, name) VALUES (187,'JP 150');
 
INSERT INTO model (brand_id, name) VALUES (188,'ATLANTIC 150');
INSERT INTO model (brand_id, name) VALUES (188,'ATLANTIC 250');
INSERT INTO model (brand_id, name) VALUES (188,'HYPE 110');
INSERT INTO model (brand_id, name) VALUES (188,'HYPE 50');
INSERT INTO model (brand_id, name) VALUES (188,'JONNY 50');
INSERT INTO model (brand_id, name) VALUES (188,'ORBIT 150');
INSERT INTO model (brand_id, name) VALUES (188,'PEGASUS 150');
INSERT INTO model (brand_id, name) VALUES (188,'QUICK 150');
INSERT INTO model (brand_id, name) VALUES (188,'TR 150');
 
INSERT INTO model (brand_id, name) VALUES (189,'125 K-LOG');
INSERT INTO model (brand_id, name) VALUES (189,'125 K-TOP');
INSERT INTO model (brand_id, name) VALUES (189,'125 TOP');
INSERT INTO model (brand_id, name) VALUES (189,'250 DUAL');
INSERT INTO model (brand_id, name) VALUES (189,'LJ-16');
 
INSERT INTO model (brand_id, name) VALUES (190,'COMET 150');
INSERT INTO model (brand_id, name) VALUES (190,'COMET 250');
INSERT INTO model (brand_id, name) VALUES (190,'COMET 650R');
INSERT INTO model (brand_id, name) VALUES (190,'COMET 650R EFI');
INSERT INTO model (brand_id, name) VALUES (190,'COMET EFI');
INSERT INTO model (brand_id, name) VALUES (190,'COMET GT 250 EFI');
INSERT INTO model (brand_id, name) VALUES (190,'COMET GT 250 R');
INSERT INTO model (brand_id, name) VALUES (190,'COMET GT 250R');
INSERT INTO model (brand_id, name) VALUES (190,'COMET GT 650R');
INSERT INTO model (brand_id, name) VALUES (190,'COMET GT-R');
INSERT INTO model (brand_id, name) VALUES (190,'COMET GTR EFI');
INSERT INTO model (brand_id, name) VALUES (190,'COMET PHASE 2');
INSERT INTO model (brand_id, name) VALUES (190,'CRUISE 125');
INSERT INTO model (brand_id, name) VALUES (190,'CRUISER II 125 CLASSIC');
INSERT INTO model (brand_id, name) VALUES (190,'CRZ 150');
INSERT INTO model (brand_id, name) VALUES (190,'CRZ 150 SM');
INSERT INTO model (brand_id, name) VALUES (190,'ERO PLUS 125');
INSERT INTO model (brand_id, name) VALUES (190,'FLASH 150');
INSERT INTO model (brand_id, name) VALUES (190,'FX 110 MIDAS');
INSERT INTO model (brand_id, name) VALUES (190,'GF 125 SPEED');
INSERT INTO model (brand_id, name) VALUES (190,'MAGIK 125');
INSERT INTO model (brand_id, name) VALUES (190,'MIRAGE 150');
INSERT INTO model (brand_id, name) VALUES (190,'MIRAGE 250 EFI');
INSERT INTO model (brand_id, name) VALUES (190,'MIRAGE 650');
INSERT INTO model (brand_id, name) VALUES (190,'MIRAGE 650 EFI');
INSERT INTO model (brand_id, name) VALUES (190,'MIRAGE POWER');
INSERT INTO model (brand_id, name) VALUES (190,'MIRAGE PREMIER');
INSERT INTO model (brand_id, name) VALUES (190,'MOTOKAR');
INSERT INTO model (brand_id, name) VALUES (190,'PRIMA 150');
INSERT INTO model (brand_id, name) VALUES (190,'PRIMA 150 GTS');
INSERT INTO model (brand_id, name) VALUES (190,'PRIMA 50');
INSERT INTO model (brand_id, name) VALUES (190,'PRIMA ELECTRA');
INSERT INTO model (brand_id, name) VALUES (190,'PRIMA RALLY 50');
INSERT INTO model (brand_id, name) VALUES (190,'RX 125');
INSERT INTO model (brand_id, name) VALUES (190,'SETA 125');
INSERT INTO model (brand_id, name) VALUES (190,'SETA 150');
INSERT INTO model (brand_id, name) VALUES (190,'SOFT 50');
INSERT INTO model (brand_id, name) VALUES (190,'SUPER CAB 100');
INSERT INTO model (brand_id, name) VALUES (190,'SUPER CAB 50');
INSERT INTO model (brand_id, name) VALUES (190,'TN 125');
INSERT INTO model (brand_id, name) VALUES (190,'WAY 125');
INSERT INTO model (brand_id, name) VALUES (190,'WIN 110');
 
INSERT INTO model (brand_id, name) VALUES (191,'Versys');
INSERT INTO model (brand_id, name) VALUES (191,'AVAJET 100');
INSERT INTO model (brand_id, name) VALUES (191,'CLASSIC 100');
INSERT INTO model (brand_id, name) VALUES (191,'CONCOURS 14');
INSERT INTO model (brand_id, name) VALUES (191,'D TRACKER 250 X');
INSERT INTO model (brand_id, name) VALUES (191,'ER 4N');
INSERT INTO model (brand_id, name) VALUES (191,'ER 5');
INSERT INTO model (brand_id, name) VALUES (191,'ER-6F');
INSERT INTO model (brand_id, name) VALUES (191,'ER-6N');
INSERT INTO model (brand_id, name) VALUES (191,'KDX 200');
INSERT INTO model (brand_id, name) VALUES (191,'KDX 220 R');
INSERT INTO model (brand_id, name) VALUES (191,'KDX 50');
INSERT INTO model (brand_id, name) VALUES (191,'KFX 450R');
INSERT INTO model (brand_id, name) VALUES (191,'KLR 250');
INSERT INTO model (brand_id, name) VALUES (191,'KLR 650');
INSERT INTO model (brand_id, name) VALUES (191,'KLX 110');
INSERT INTO model (brand_id, name) VALUES (191,'KLX 125');
INSERT INTO model (brand_id, name) VALUES (191,'KLX 125 L');
INSERT INTO model (brand_id, name) VALUES (191,'KLX 250');
INSERT INTO model (brand_id, name) VALUES (191,'KLX 300R');
INSERT INTO model (brand_id, name) VALUES (191,'KLX 400R');
INSERT INTO model (brand_id, name) VALUES (191,'KLX 400SR');
INSERT INTO model (brand_id, name) VALUES (191,'KLX 450R');
INSERT INTO model (brand_id, name) VALUES (191,'KLX 650');
INSERT INTO model (brand_id, name) VALUES (191,'KX 100');
INSERT INTO model (brand_id, name) VALUES (191,'KX 125');
INSERT INTO model (brand_id, name) VALUES (191,'KX 250');
INSERT INTO model (brand_id, name) VALUES (191,'KX 250F');
INSERT INTO model (brand_id, name) VALUES (191,'KX 450F');
INSERT INTO model (brand_id, name) VALUES (191,'KX 500');
INSERT INTO model (brand_id, name) VALUES (191,'KX 60');
INSERT INTO model (brand_id, name) VALUES (191,'KX 65');
INSERT INTO model (brand_id, name) VALUES (191,'KX 85');
INSERT INTO model (brand_id, name) VALUES (191,'KZ 1000');
INSERT INTO model (brand_id, name) VALUES (191,'KZ 1300');
INSERT INTO model (brand_id, name) VALUES (191,'MAXI II 100');
INSERT INTO model (brand_id, name) VALUES (191,'MOJAVE 250');
INSERT INTO model (brand_id, name) VALUES (191,'NINJA 250R');
INSERT INTO model (brand_id, name) VALUES (191,'NINJA 650R');
INSERT INTO model (brand_id, name) VALUES (191,'NINJA EX 500');
INSERT INTO model (brand_id, name) VALUES (191,'NINJA ZX-10');
INSERT INTO model (brand_id, name) VALUES (191,'NINJA ZX-10R');
INSERT INTO model (brand_id, name) VALUES (191,'NINJA ZX-11');
INSERT INTO model (brand_id, name) VALUES (191,'NINJA ZX-12R');
INSERT INTO model (brand_id, name) VALUES (191,'NINJA ZX-14');
INSERT INTO model (brand_id, name) VALUES (191,'NINJA ZX-6R 600cc');
INSERT INTO model (brand_id, name) VALUES (191,'NINJA ZX-6R 636 cc');
INSERT INTO model (brand_id, name) VALUES (191,'NINJA ZX-7R');
INSERT INTO model (brand_id, name) VALUES (191,'NINJA ZX-9R');
INSERT INTO model (brand_id, name) VALUES (191,'VERSYS');
INSERT INTO model (brand_id, name) VALUES (191,'VOYAGER 1200');
INSERT INTO model (brand_id, name) VALUES (191,'VOYAGER XII');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN 1500');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN 1500 CLASSIC');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN 1500 DRIFTER');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN 1500 MEAN STREAK');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN 1500 NOMAD FI');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN 1600 CLASSIC');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN 1600 MEAN STREAK');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN 1700');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN 2000');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN 750');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN 800');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN 800 CLASSIC');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN 800 DRIFTER');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN 900 CLASSIC');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN 900 CLASSIC LT'); 
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN 900 CUSTOM');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN EN 500');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN LTD CLASS 500');
INSERT INTO model (brand_id, name) VALUES (191,'VULCAN NOMAD 1500');
INSERT INTO model (brand_id, name) VALUES (191,'Z1000');
INSERT INTO model (brand_id, name) VALUES (191,'Z750');
INSERT INTO model (brand_id, name) VALUES (191,'ZR-7');
INSERT INTO model (brand_id, name) VALUES (191,'ZR-7S');
INSERT INTO model (brand_id, name) VALUES (191,'ZZR 1200');
INSERT INTO model (brand_id, name) VALUES (191,'ZZR 1400');
 
INSERT INTO model (brand_id, name) VALUES (192,'DJW 50');
INSERT INTO model (brand_id, name) VALUES (192,'M BOY 90');
INSERT INTO model (brand_id, name) VALUES (192,'PEOPLE 50');
INSERT INTO model (brand_id, name) VALUES (192,'ZING 150');
 
INSERT INTO model (brand_id, name) VALUES (193,'VIP 350 EL');
 
INSERT INTO model (brand_id, name) VALUES (194,'990 ADVENTURE ABS DAKAR');
INSERT INTO model (brand_id, name) VALUES (194,'ADVENTURE 640');
INSERT INTO model (brand_id, name) VALUES (194,'ADVENTURE 950');
INSERT INTO model (brand_id, name) VALUES (194,'ADVENTURE 990');
INSERT INTO model (brand_id, name) VALUES (194,'ADVENTURE 990 DAKAR');
INSERT INTO model (brand_id, name) VALUES (194,'DUKE 640');
INSERT INTO model (brand_id, name) VALUES (194,'DUKE II 640');
INSERT INTO model (brand_id, name) VALUES (194,'ENDURO 690');
INSERT INTO model (brand_id, name) VALUES (194,'ENDURO 690R');
INSERT INTO model (brand_id, name) VALUES (194,'EXC 125');
INSERT INTO model (brand_id, name) VALUES (194,'EXC 200');
INSERT INTO model (brand_id, name) VALUES (194,'EXC 250');
INSERT INTO model (brand_id, name) VALUES (194,'EXC 250 2T');
INSERT INTO model (brand_id, name) VALUES (194,'EXC 250 4T');
INSERT INTO model (brand_id, name) VALUES (194,'EXC 250F');
INSERT INTO model (brand_id, name) VALUES (194,'EXC 300');
INSERT INTO model (brand_id, name) VALUES (194,'EXC 380');
INSERT INTO model (brand_id, name) VALUES (194,'EXC 400');
INSERT INTO model (brand_id, name) VALUES (194,'EXC 450');
INSERT INTO model (brand_id, name) VALUES (194,'EXC 450R');
INSERT INTO model (brand_id, name) VALUES (194,'EXC 520');
INSERT INTO model (brand_id, name) VALUES (194,'EXC 525');
INSERT INTO model (brand_id, name) VALUES (194,'EXC 530R');
INSERT INTO model (brand_id, name) VALUES (194,'LC4 640');
INSERT INTO model (brand_id, name) VALUES (194,'RC8 1190');
INSERT INTO model (brand_id, name) VALUES (194,'RC8 R');
INSERT INTO model (brand_id, name) VALUES (194,'SC 400');
INSERT INTO model (brand_id, name) VALUES (194,'SC 620');
INSERT INTO model (brand_id, name) VALUES (194,'SUPER ENDURO 950');
INSERT INTO model (brand_id, name) VALUES (194,'SUPERDUKE 990');
INSERT INTO model (brand_id, name) VALUES (194,'SUPERMOTO 690');
INSERT INTO model (brand_id, name) VALUES (194,'SUPERMOTO 950R');
INSERT INTO model (brand_id, name) VALUES (194,'SUPERMOTO 990T');
INSERT INTO model (brand_id, name) VALUES (194,'SX 125');
INSERT INTO model (brand_id, name) VALUES (194,'SX 150');
INSERT INTO model (brand_id, name) VALUES (194,'SX 250');
INSERT INTO model (brand_id, name) VALUES (194,'SX 250F');
INSERT INTO model (brand_id, name) VALUES (194,'SX 350F');
INSERT INTO model (brand_id, name) VALUES (194,'SX 450');
INSERT INTO model (brand_id, name) VALUES (194,'SX 450F');
INSERT INTO model (brand_id, name) VALUES (194,'SX 50');
INSERT INTO model (brand_id, name) VALUES (194,'SX 65');
INSERT INTO model (brand_id, name) VALUES (194,'SX 85');
INSERT INTO model (brand_id, name) VALUES (194,'SXC 520');
INSERT INTO model (brand_id, name) VALUES (194,'SXC 625');
INSERT INTO model (brand_id, name) VALUES (194,'XCF 250W');
 
INSERT INTO model (brand_id, name) VALUES (195,'AKROS 50');
INSERT INTO model (brand_id, name) VALUES (195,'AKROS 90');
INSERT INTO model (brand_id, name) VALUES (195,'ERGON 50');
INSERT INTO model (brand_id, name) VALUES (195,'NIX 50');
INSERT INTO model (brand_id, name) VALUES (195,'PALIO 50');

INSERT INTO model (brand_id, name) VALUES (196,'LD 150');
 
INSERT INTO model (brand_id, name) VALUES (197,'ML 200 CHOPPER');
 
INSERT INTO model (brand_id, name) VALUES (198,'LY 125T-5');
INSERT INTO model (brand_id, name) VALUES (198,'LY 150T-5');
INSERT INTO model (brand_id, name) VALUES (198,'LY 150T-6A');
INSERT INTO model (brand_id, name) VALUES (198,'LY 150T-7A');
INSERT INTO model (brand_id, name) VALUES (198,'ZN 151F DELUXE');
INSERT INTO model (brand_id, name) VALUES (198,'ZN 152F DELUXE');
 
INSERT INTO model (brand_id, name) VALUES (199,'CIAK MASTER 200');
INSERT INTO model (brand_id, name) VALUES (199,'FIREFOX F15');
INSERT INTO model (brand_id, name) VALUES (199,'GRIZZLY 12');
INSERT INTO model (brand_id, name) VALUES (199,'PASSWORD 250');
INSERT INTO model (brand_id, name) VALUES (199,'SPIDERMAX GT500');

INSERT INTO model (brand_id, name) VALUES (200,'MBW 125');
INSERT INTO model (brand_id, name) VALUES (200,'MBW 150');
INSERT INTO model (brand_id, name) VALUES (200,'MBW 250');
INSERT INTO model (brand_id, name) VALUES (200,'MBW 50');
INSERT INTO model (brand_id, name) VALUES (200,'MBW SUPER 150');
 
INSERT INTO model (brand_id, name) VALUES (201,'DRAGO LJ 150-7');
INSERT INTO model (brand_id, name) VALUES (201,'EASY LJ 110-10');
INSERT INTO model (brand_id, name) VALUES (201,'FAST LJ 150-2');
INSERT INTO model (brand_id, name) VALUES (201,'SKEMA LJ 125-6');
INSERT INTO model (brand_id, name) VALUES (201,'VITE LJ 150T-7');
 
INSERT INTO model (brand_id, name) VALUES (202,'H6');
 
INSERT INTO model (brand_id, name) VALUES (203,'BELLAGIO');
INSERT INTO model (brand_id, name) VALUES (203,'CALIFÓRNIA EV');
INSERT INTO model (brand_id, name) VALUES (203,'CALIFÓRNIA JACKAL');
INSERT INTO model (brand_id, name) VALUES (203,'CALIFÓRNIA SPECIAL');
INSERT INTO model (brand_id, name) VALUES (203,'CALIFÓRNIA STONE');
INSERT INTO model (brand_id, name) VALUES (203,'QUOTA 1100 ES');
INSERT INTO model (brand_id, name) VALUES (203,'V11 LE MANS');
INSERT INTO model (brand_id, name) VALUES (203,'V11 SPORT');
 
INSERT INTO model (brand_id, name) VALUES (204,'CUB 110');
INSERT INTO model (brand_id, name) VALUES (204,'S 1000');
INSERT INTO model (brand_id, name) VALUES (204,'S 500');
INSERT INTO model (brand_id, name) VALUES (204,'S 800');
INSERT INTO model (brand_id, name) VALUES (204,'SCO 150');
INSERT INTO model (brand_id, name) VALUES (204,'SCO 50');
INSERT INTO model (brand_id, name) VALUES (204,'SS 500');
INSERT INTO model (brand_id, name) VALUES (204,'SS 800');
INSERT INTO model (brand_id, name) VALUES (204,'V 1500');
INSERT INTO model (brand_id, name) VALUES (204,'V 500');

INSERT INTO model (brand_id, name) VALUES (205,'MOTOVI 1200');
 
INSERT INTO model (brand_id, name) VALUES (206,'230 SUPERMOTARD');
INSERT INTO model (brand_id, name) VALUES (206,'230R SUPERCROSS');
INSERT INTO model (brand_id, name) VALUES (206,'BLACK JACK');
 
INSERT INTO model (brand_id, name) VALUES (207,'BRUTALE 910');
INSERT INTO model (brand_id, name) VALUES (207,'BRUTALE 910R');
INSERT INTO model (brand_id, name) VALUES (207,'BRUTALE 910S');
INSERT INTO model (brand_id, name) VALUES (207,'BRUTALE AMERICA');
INSERT INTO model (brand_id, name) VALUES (207,'BRUTALE GLADIO');
INSERT INTO model (brand_id, name) VALUES (207,'BRUTALE S');
INSERT INTO model (brand_id, name) VALUES (207,'BRUTALE STARFIGHTER');
INSERT INTO model (brand_id, name) VALUES (207,'BRUTALE STARFIGHTER TITANIUM R');
INSERT INTO model (brand_id, name) VALUES (207,'F4 1000 1+1');
INSERT INTO model (brand_id, name) VALUES (207,'F4 1000R');
INSERT INTO model (brand_id, name) VALUES (207,'F4 1000R 1+1');
INSERT INTO model (brand_id, name) VALUES (207,'F4 1000S');
INSERT INTO model (brand_id, name) VALUES (207,'F4 312 R');
INSERT INTO model (brand_id, name) VALUES (207,'F4 312 R 1+1');
INSERT INTO model (brand_id, name) VALUES (207,'F4 750');
INSERT INTO model (brand_id, name) VALUES (207,'F4 750S');
INSERT INTO model (brand_id, name) VALUES (207,'F4 CORSE');
INSERT INTO model (brand_id, name) VALUES (207,'F4 MAMBA');
INSERT INTO model (brand_id, name) VALUES (207,'F4 SENNA');
INSERT INTO model (brand_id, name) VALUES (207,'F4 TAMBURINI');
INSERT INTO model (brand_id, name) VALUES (207,'F4 VELTRO');
 
INSERT INTO model (brand_id, name) VALUES (208,'BIG FORCE 250');
INSERT INTO model (brand_id, name) VALUES (208,'BIG FORCE 250 II');
INSERT INTO model (brand_id, name) VALUES (208,'BLACK STAR 125');
INSERT INTO model (brand_id, name) VALUES (208,'BLACK STAR 150');
INSERT INTO model (brand_id, name) VALUES (208,'BRX 140');
INSERT INTO model (brand_id, name) VALUES (208,'BRX 250');
INSERT INTO model (brand_id, name) VALUES (208,'DUAL 200');
INSERT INTO model (brand_id, name) VALUES (208,'FENIX 200');
INSERT INTO model (brand_id, name) VALUES (208,'FOX 100');
INSERT INTO model (brand_id, name) VALUES (208,'FOX 110');
INSERT INTO model (brand_id, name) VALUES (208,'GO 100');
INSERT INTO model (brand_id, name) VALUES (208,'HALLEY 150');
INSERT INTO model (brand_id, name) VALUES (208,'HALLEY 200');
INSERT INTO model (brand_id, name) VALUES (208,'JURASIC 300');
INSERT INTO model (brand_id, name) VALUES (208,'MA 100 3B');
INSERT INTO model (brand_id, name) VALUES (208,'MA 125 GY');
INSERT INTO model (brand_id, name) VALUES (208,'SIMBA 50');
INSERT INTO model (brand_id, name) VALUES (208,'SPORT 110');
INSERT INTO model (brand_id, name) VALUES (208,'SPORT 150');
INSERT INTO model (brand_id, name) VALUES (208,'STREET 150');
INSERT INTO model (brand_id, name) VALUES (208,'SUPER 125');
INSERT INTO model (brand_id, name) VALUES (208,'SUPER X 125R');
INSERT INTO model (brand_id, name) VALUES (208,'WY 50Q T-3 SCOOTER');
INSERT INTO model (brand_id, name) VALUES (208,'X-CAPE 200');
INSERT INTO model (brand_id, name) VALUES (208,'XRT 110');
 
INSERT INTO model (brand_id, name) VALUES (209,'AX 100');
INSERT INTO model (brand_id, name) VALUES (209,'AX 100-A');
INSERT INTO model (brand_id, name) VALUES (209,'JC 125');
INSERT INTO model (brand_id, name) VALUES (209,'JC 125-2');
INSERT INTO model (brand_id, name) VALUES (209,'JC 125-8');
INSERT INTO model (brand_id, name) VALUES (209,'QM 50');
 
INSERT INTO model (brand_id, name) VALUES (210,'BR III');
 
INSERT INTO model (brand_id, name) VALUES (211,'BUXY 50');
INSERT INTO model (brand_id, name) VALUES (211,'ELYSEO 125');
INSERT INTO model (brand_id, name) VALUES (211,'SCOOT ELEC');
INSERT INTO model (brand_id, name) VALUES (211,'SPEEDAKE 50');
INSERT INTO model (brand_id, name) VALUES (211,'SPEEDFIGHT 100');
INSERT INTO model (brand_id, name) VALUES (211,'SPEEDFIGHT 50');
INSERT INTO model (brand_id, name) VALUES (211,'SPEEDFIGHT 50 LC');
INSERT INTO model (brand_id, name) VALUES (211,'SQUAB 50');
INSERT INTO model (brand_id, name) VALUES (211,'TREKKER 100');
INSERT INTO model (brand_id, name) VALUES (211,'VIVACITY 50');
INSERT INTO model (brand_id, name) VALUES (211,'ZENITH 50');
 
INSERT INTO model (brand_id, name) VALUES (212,'BEVERLY 200');
INSERT INTO model (brand_id, name) VALUES (212,'BEVERLY 250');
INSERT INTO model (brand_id, name) VALUES (212,'BEVERLY 500');
INSERT INTO model (brand_id, name) VALUES (212,'BEVERLY CRUISER 250');
INSERT INTO model (brand_id, name) VALUES (212,'BEVERLY CRUISER 500');
INSERT INTO model (brand_id, name) VALUES (212,'BEVERLY TOURER 300');
INSERT INTO model (brand_id, name) VALUES (212,'LIBERTY 200');
INSERT INTO model (brand_id, name) VALUES (212,'LIBERTY S 200');
INSERT INTO model (brand_id, name) VALUES (212,'MP3 400 RL');
INSERT INTO model (brand_id, name) VALUES (212,'NRG MC3 DD');
INSERT INTO model (brand_id, name) VALUES (212,'RUNNER 50');
INSERT INTO model (brand_id, name) VALUES (212,'VESPA GTS 250 I.E');
INSERT INTO model (brand_id, name) VALUES (212,'VESPA GTS 250 I.E ABS');
INSERT INTO model (brand_id, name) VALUES (212,'VESPA GTV 250 I.E');
INSERT INTO model (brand_id, name) VALUES (212,'VESPA LX 125');
INSERT INTO model (brand_id, name) VALUES (212,'VESPA LX 150');
INSERT INTO model (brand_id, name) VALUES (212,'VESPA PX 150 ORIGINALE');
INSERT INTO model (brand_id, name) VALUES (212,'VESPA PX 200');
INSERT INTO model (brand_id, name) VALUES (212,'ZIP 50');

INSERT INTO model (brand_id, name) VALUES (213,'TRAIL BROSS 325');

INSERT INTO model (brand_id, name) VALUES (214,'BLACK JACK');
INSERT INTO model (brand_id, name) VALUES (214,'FENIX GOLD');
INSERT INTO model (brand_id, name) VALUES (214,'GHOST');
INSERT INTO model (brand_id, name) VALUES (214,'GHOST 320');
INSERT INTO model (brand_id, name) VALUES (214,'SPYDER 270');
INSERT INTO model (brand_id, name) VALUES (214,'SPYDER 320');

INSERT INTO model (brand_id, name) VALUES (215,'TRC01 VERSÃO I');
INSERT INTO model (brand_id, name) VALUES (215,'TRC01 VERSÃO II');

INSERT INTO model (brand_id, name) VALUES (216,'MADASS');

INSERT INTO model (brand_id, name) VALUES (217,'ENJOY 50');
INSERT INTO model (brand_id, name) VALUES (217,'HUSKY 150');
INSERT INTO model (brand_id, name) VALUES (217,'PASSING 110');
 
INSERT INTO model (brand_id, name) VALUES (218,'WY 150-EX');
INSERT INTO model (brand_id, name) VALUES (218,'XY 110-V WAVE');
INSERT INTO model (brand_id, name) VALUES (218,'XY 125-14');
INSERT INTO model (brand_id, name) VALUES (218,'XY 150 GY');
INSERT INTO model (brand_id, name) VALUES (218,'XY 150-5 SPEED');
INSERT INTO model (brand_id, name) VALUES (218,'XY 150-STA');
INSERT INTO model (brand_id, name) VALUES (218,'XY 200 lll');
INSERT INTO model (brand_id, name) VALUES (218,'XY 200-5');
INSERT INTO model (brand_id, name) VALUES (218,'XY 250 STVI');
INSERT INTO model (brand_id, name) VALUES (218,'XY 250-5');
INSERT INTO model (brand_id, name) VALUES (218,'XY 50 Q');
INSERT INTO model (brand_id, name) VALUES (218,'XY 50 Q-2');
INSERT INTO model (brand_id, name) VALUES (218,'XY 50Q EAGLE');
INSERT INTO model (brand_id, name) VALUES (218,'XY 50Q PHOENIX');
 
INSERT INTO model (brand_id, name) VALUES (219,'AKROS 50');
 
INSERT INTO model (brand_id, name) VALUES (220,'AKROS 50');
INSERT INTO model (brand_id, name) VALUES (220,'AKROS 90');
INSERT INTO model (brand_id, name) VALUES (220,'ERGON 50');
INSERT INTO model (brand_id, name) VALUES (220,'FIFTY 50');
INSERT INTO model (brand_id, name) VALUES (220,'FUTURE');
INSERT INTO model (brand_id, name) VALUES (220,'FUTURE ELÉTRICA');
INSERT INTO model (brand_id, name) VALUES (220,'FUTURE SPORT');
INSERT INTO model (brand_id, name) VALUES (220,'HAWK 150');
INSERT INTO model (brand_id, name) VALUES (220,'HUNTER 100');
INSERT INTO model (brand_id, name) VALUES (220,'HUNTER 90');
INSERT INTO model (brand_id, name) VALUES (220,'HUNTER SE');
INSERT INTO model (brand_id, name) VALUES (220,'MAX SE');
INSERT INTO model (brand_id, name) VALUES (220,'MAX SED');
INSERT INTO model (brand_id, name) VALUES (220,'MOTARD');
INSERT INTO model (brand_id, name) VALUES (220,'MOTARD 200');
INSERT INTO model (brand_id, name) VALUES (220,'OUTLOOK 150');
INSERT INTO model (brand_id, name) VALUES (220,'PALIO 50');
INSERT INTO model (brand_id, name) VALUES (220,'PGO SPEED 50');
INSERT INTO model (brand_id, name) VALUES (220,'PGO SPEED 90');
INSERT INTO model (brand_id, name) VALUES (220,'STX');
INSERT INTO model (brand_id, name) VALUES (220,'STX 200');
INSERT INTO model (brand_id, name) VALUES (220,'SUPER FIFTY 50');
INSERT INTO model (brand_id, name) VALUES (220,'VBLADE');
INSERT INTO model (brand_id, name) VALUES (220,'WEB');
INSERT INTO model (brand_id, name) VALUES (220,'WEB EVO');
 
INSERT INTO model (brand_id, name) VALUES (221,'ADDRESS 100');
INSERT INTO model (brand_id, name) VALUES (221,'ADDRESS 50');
INSERT INTO model (brand_id, name) VALUES (221,'AE 50');
INSERT INTO model (brand_id, name) VALUES (221,'AG 100');
INSERT INTO model (brand_id, name) VALUES (221,'AN125 BURGMAN');
INSERT INTO model (brand_id, name) VALUES (221,'AN650 BURGMAN');
INSERT INTO model (brand_id, name) VALUES (221,'B-KING');
INSERT INTO model (brand_id, name) VALUES (221,'BANDIT 1200S');
INSERT INTO model (brand_id, name) VALUES (221,'BANDIT 1250');
INSERT INTO model (brand_id, name) VALUES (221,'BANDIT 1250F');
INSERT INTO model (brand_id, name) VALUES (221,'BANDIT 1250S');
INSERT INTO model (brand_id, name) VALUES (221,'BANDIT 600S');
INSERT INTO model (brand_id, name) VALUES (221,'BANDIT 650');
INSERT INTO model (brand_id, name) VALUES (221,'BANDIT 650S');
INSERT INTO model (brand_id, name) VALUES (221,'BANDIT N1200');
INSERT INTO model (brand_id, name) VALUES (221,'BANDIT N1250');
INSERT INTO model (brand_id, name) VALUES (221,'BANDIT N600');
INSERT INTO model (brand_id, name) VALUES (221,'BANDIT N650');
INSERT INTO model (brand_id, name) VALUES (221,'BOULEVARD M109R');
INSERT INTO model (brand_id, name) VALUES (221,'BOULEVARD M1500');
INSERT INTO model (brand_id, name) VALUES (221,'BOULEVARD M800');
INSERT INTO model (brand_id, name) VALUES (221,'BURGMAN 125 AUTOMATIC');
INSERT INTO model (brand_id, name) VALUES (221,'BURGMAN 400');
INSERT INTO model (brand_id, name) VALUES (221,'BURGMAN 650');
INSERT INTO model (brand_id, name) VALUES (221,'BURGMAN 650 EXECUTIVE');
INSERT INTO model (brand_id, name) VALUES (221,'C 1500 BOULEVARD');
INSERT INTO model (brand_id, name) VALUES (221,'DL 1000 V-STROM');
INSERT INTO model (brand_id, name) VALUES (221,'DL 650 V-STROM');
INSERT INTO model (brand_id, name) VALUES (221,'DR 350');
INSERT INTO model (brand_id, name) VALUES (221,'DR 350 SE');
INSERT INTO model (brand_id, name) VALUES (221,'DR 650 R');
INSERT INTO model (brand_id, name) VALUES (221,'DR 650 RE');
INSERT INTO model (brand_id, name) VALUES (221,'DR 650 RS');
INSERT INTO model (brand_id, name) VALUES (221,'DR 650 RSE');
INSERT INTO model (brand_id, name) VALUES (221,'DR 800 S');
INSERT INTO model (brand_id, name) VALUES (221,'DR-Z 400E');
INSERT INTO model (brand_id, name) VALUES (221,'EN 125 YES ED');
INSERT INTO model (brand_id, name) VALUES (221,'EN 125 YES ED CARGO');
INSERT INTO model (brand_id, name) VALUES (221,'FREEWIND XF 650');
INSERT INTO model (brand_id, name) VALUES (221,'GS500E');
INSERT INTO model (brand_id, name) VALUES (221,'GSX 1100 F');
INSERT INTO model (brand_id, name) VALUES (221,'GSX 1100 SBE KATANA');
INSERT INTO model (brand_id, name) VALUES (221,'GSX 1300 B-KING');
INSERT INTO model (brand_id, name) VALUES (221,'GSX 650 F');
INSERT INTO model (brand_id, name) VALUES (221,'GSX 750 F');
INSERT INTO model (brand_id, name) VALUES (221,'GSX R1000');
INSERT INTO model (brand_id, name) VALUES (221,'GSX-R 750');
INSERT INTO model (brand_id, name) VALUES (221,'GSX-R1000');
INSERT INTO model (brand_id, name) VALUES (221,'GSX-R1100 W');
INSERT INTO model (brand_id, name) VALUES (221,'GSX-R600');
INSERT INTO model (brand_id, name) VALUES (221,'GSX-R750 W');
INSERT INTO model (brand_id, name) VALUES (221,'GSX-R750 W SRAD');
INSERT INTO model (brand_id, name) VALUES (221,'GSX1300R HAYABUSA');
INSERT INTO model (brand_id, name) VALUES (221,'GT 550');
INSERT INTO model (brand_id, name) VALUES (221,'INTRUDER 125');
INSERT INTO model (brand_id, name) VALUES (221,'INTRUDER 125 ED CARGO');
INSERT INTO model (brand_id, name) VALUES (221,'INTRUDER 250');
INSERT INTO model (brand_id, name) VALUES (221,'INTRUDER VS 1400 GLP');
INSERT INTO model (brand_id, name) VALUES (221,'INTRUDER VS 800 GL');
INSERT INTO model (brand_id, name) VALUES (221,'INTRUDER VS 800 GLP');
INSERT INTO model (brand_id, name) VALUES (221,'KATANA 125');
INSERT INTO model (brand_id, name) VALUES (221,'LC 1500 INTRUDER');
INSERT INTO model (brand_id, name) VALUES (221,'LETS II 50');
INSERT INTO model (brand_id, name) VALUES (221,'LS 650 SAVAGE');
INSERT INTO model (brand_id, name) VALUES (221,'LT 50 QUADRICICLO');
INSERT INTO model (brand_id, name) VALUES (221,'LT 80 QUADRICICLO');
INSERT INTO model (brand_id, name) VALUES (221,'LT F160 QUADRICICLO');
INSERT INTO model (brand_id, name) VALUES (221,'LT-A400F KINGQUAD');
INSERT INTO model (brand_id, name) VALUES (221,'LT-A450X KINGQUAD');
INSERT INTO model (brand_id, name) VALUES (221,'LT-A750X KINGQUAD');
INSERT INTO model (brand_id, name) VALUES (221,'LT-F250 OZARK');
INSERT INTO model (brand_id, name) VALUES (221,'LT-R450 QUADRACER');
INSERT INTO model (brand_id, name) VALUES (221,'MARAUDER 800');
INSERT INTO model (brand_id, name) VALUES (221,'OZARK 250');
INSERT INTO model (brand_id, name) VALUES (221,'QUADRACER R450');
INSERT INTO model (brand_id, name) VALUES (221,'QUADRUNNER 160');
INSERT INTO model (brand_id, name) VALUES (221,'QUADSPORT Z400');
INSERT INTO model (brand_id, name) VALUES (221,'RF 600 R');
INSERT INTO model (brand_id, name) VALUES (221,'RF 900 R');
INSERT INTO model (brand_id, name) VALUES (221,'RM 125');
INSERT INTO model (brand_id, name) VALUES (221,'RM 250');
INSERT INTO model (brand_id, name) VALUES (221,'RM 80');
INSERT INTO model (brand_id, name) VALUES (221,'RM-Z 250');
INSERT INTO model (brand_id, name) VALUES (221,'RMX 250');
INSERT INTO model (brand_id, name) VALUES (221,'TL 1000 S');
INSERT INTO model (brand_id, name) VALUES (221,'VX 800');
INSERT INTO model (brand_id, name) VALUES (221,'YES 125 ED');
INSERT INTO model (brand_id, name) VALUES (221,'YES SE');
INSERT INTO model (brand_id, name) VALUES (221,'YES SE CARGO');
INSERT INTO model (brand_id, name) VALUES (221,'ZX-14');
 
INSERT INTO model (brand_id, name) VALUES (222,'BEST JH125G');
INSERT INTO model (brand_id, name) VALUES (222,'CJ 50 F');
INSERT INTO model (brand_id, name) VALUES (222,'FLY JH125L');
INSERT INTO model (brand_id, name) VALUES (222,'JH 50');
INSERT INTO model (brand_id, name) VALUES (222,'JH 70');
INSERT INTO model (brand_id, name) VALUES (222,'JH 70 III');
INSERT INTO model (brand_id, name) VALUES (222,'JOTO 125');
INSERT INTO model (brand_id, name) VALUES (222,'JOTO 135');
INSERT INTO model (brand_id, name) VALUES (222,'MONTEZ 250');
INSERT INTO model (brand_id, name) VALUES (222,'PRINCE JL 110-11');
INSERT INTO model (brand_id, name) VALUES (222,'SHARK 250');
INSERT INTO model (brand_id, name) VALUES (222,'SKY 125');
INSERT INTO model (brand_id, name) VALUES (222,'SKY JL 110-3');
INSERT INTO model (brand_id, name) VALUES (222,'SKY JL 110-8');
INSERT INTO model (brand_id, name) VALUES (222,'STAR JL 50 Q-2');
INSERT INTO model (brand_id, name) VALUES (222,'VICO');
INSERT INTO model (brand_id, name) VALUES (222,'WORK 125');

INSERT INTO model (brand_id, name) VALUES (223,'ADVENTURER');
INSERT INTO model (brand_id, name) VALUES (223,'BONNEVILE');
INSERT INTO model (brand_id, name) VALUES (223,'BONNEVILLE T 100 790');
INSERT INTO model (brand_id, name) VALUES (223,'BONNEVILLE T 100 865');
INSERT INTO model (brand_id, name) VALUES (223,'DAYTONA 1200');
INSERT INTO model (brand_id, name) VALUES (223,'DAYTONA 675');
INSERT INTO model (brand_id, name) VALUES (223,'DAYTONA 900');
INSERT INTO model (brand_id, name) VALUES (223,'DAYTONA 955i');
INSERT INTO model (brand_id, name) VALUES (223,'DAYTONA SUPER III');
INSERT INTO model (brand_id, name) VALUES (223,'DAYTONA T 955');
INSERT INTO model (brand_id, name) VALUES (223,'LEGEND 900');
INSERT INTO model (brand_id, name) VALUES (223,'ROCKET III');
INSERT INTO model (brand_id, name) VALUES (223,'ROCKET III CLASSIC');
INSERT INTO model (brand_id, name) VALUES (223,'ROCKET III TOURING');
INSERT INTO model (brand_id, name) VALUES (223,'SCRAMBLER');
INSERT INTO model (brand_id, name) VALUES (223,'SPEED TRIPLE'); 
INSERT INTO model (brand_id, name) VALUES (223,'SPEED TRIPLE 1050');
INSERT INTO model (brand_id, name) VALUES (223,'SPEED TRIPLE 1050 SE');
INSERT INTO model (brand_id, name) VALUES (223,'SPEED TRIPLE 1050i');
INSERT INTO model (brand_id, name) VALUES (223,'SPEED TRIPLE 900');
INSERT INTO model (brand_id, name) VALUES (223,'SPEED TRIPLE 955i');
INSERT INTO model (brand_id, name) VALUES (223,'SPEED TRIPLE T 509 900');
INSERT INTO model (brand_id, name) VALUES (223,'SPRINT 900');
INSERT INTO model (brand_id, name) VALUES (223,'SPRINT RS 955');
INSERT INTO model (brand_id, name) VALUES (223,'SPRINT ST');
INSERT INTO model (brand_id, name) VALUES (223,'SPRINT ST 1050');
INSERT INTO model (brand_id, name) VALUES (223,'STREET TRIPLE');
INSERT INTO model (brand_id, name) VALUES (223,'STREET TRIPLE 675');
INSERT INTO model (brand_id, name) VALUES (223,'THUNDERBIRD 900');
INSERT INTO model (brand_id, name) VALUES (223,'THUNDERBIRD 900 SPORT');
INSERT INTO model (brand_id, name) VALUES (223,'TIGER 1050');
INSERT INTO model (brand_id, name) VALUES (223,'TIGER 1050 SE');
INSERT INTO model (brand_id, name) VALUES (223,'TIGER 750');
INSERT INTO model (brand_id, name) VALUES (223,'TIGER 900');
INSERT INTO model (brand_id, name) VALUES (223,'TIGER 955i');
INSERT INTO model (brand_id, name) VALUES (223,'TIGER S');
INSERT INTO model (brand_id, name) VALUES (223,'TIGER T');
INSERT INTO model (brand_id, name) VALUES (223,'TIGER X');
INSERT INTO model (brand_id, name) VALUES (223,'TRIDENT 750');
INSERT INTO model (brand_id, name) VALUES (223,'TRIDENT 900');
INSERT INTO model (brand_id, name) VALUES (223,'TROPHY 1200');
INSERT INTO model (brand_id, name) VALUES (223,'TROPHY 900');
INSERT INTO model (brand_id, name) VALUES (223,'TT 600');

INSERT INTO model (brand_id, name) VALUES (224,'PHANTERA GT5');
INSERT INTO model (brand_id, name) VALUES (224,'PHANTOM GT5');
INSERT INTO model (brand_id, name) VALUES (224,'PHANTOM R4');
INSERT INTO model (brand_id, name) VALUES (224,'REBELLIAN');
INSERT INTO model (brand_id, name) VALUES (224,'TRITON GT5');
INSERT INTO model (brand_id, name) VALUES (224,'TRITON R4');
INSERT INTO model (brand_id, name) VALUES (224,'WORKMAN');
INSERT INTO model (brand_id, name) VALUES (224,'ZIP GT5 TURBOCAM');
INSERT INTO model (brand_id, name) VALUES (224,'ZIP R3I TURBOCAM');
 
INSERT INTO model (brand_id, name) VALUES (225,'WY125-ESD');
INSERT INTO model (brand_id, name) VALUES (225,'WY125-ESD PLUS');
INSERT INTO model (brand_id, name) VALUES (225,'WY150-EX');
 
INSERT INTO model (brand_id, name) VALUES (226,'AXIS 90');
INSERT INTO model (brand_id, name) VALUES (226,'BWS 50');
INSERT INTO model (brand_id, name) VALUES (226,'CRYPTON 100');
INSERT INTO model (brand_id, name) VALUES (226,'CRYPTON ED');
INSERT INTO model (brand_id, name) VALUES (226,'CRYPTON K');
INSERT INTO model (brand_id, name) VALUES (226,'DRAG STAR 1100');
INSERT INTO model (brand_id, name) VALUES (226,'DRAG STAR 650');
INSERT INTO model (brand_id, name) VALUES (226,'DT 180');
INSERT INTO model (brand_id, name) VALUES (226,'DT 180Z');
INSERT INTO model (brand_id, name) VALUES (226,'DT 200');
INSERT INTO model (brand_id, name) VALUES (226,'DT 200R');
INSERT INTO model (brand_id, name) VALUES (226,'FACTOR YBR 125 ED');
INSERT INTO model (brand_id, name) VALUES (226,'FAZER 250IE LIMITED EDITION');
INSERT INTO model (brand_id, name) VALUES (226,'FAZER 600');
INSERT INTO model (brand_id, name) VALUES (226,'FAZER 600S');
INSERT INTO model (brand_id, name) VALUES (226,'FAZER 8');
INSERT INTO model (brand_id, name) VALUES (226,'FAZER YS 250');
INSERT INTO model (brand_id, name) VALUES (226,'FJR 1300');
INSERT INTO model (brand_id, name) VALUES (226,'FZ1');
INSERT INTO model (brand_id, name) VALUES (226,'FZ1 FAZER');
INSERT INTO model (brand_id, name) VALUES (226,'FZ6N');
INSERT INTO model (brand_id, name) VALUES (226,'FZ6S');
INSERT INTO model (brand_id, name) VALUES (226,'FZ8');
INSERT INTO model (brand_id, name) VALUES (226,'FZR 1000');
INSERT INTO model (brand_id, name) VALUES (226,'FZR 600');
INSERT INTO model (brand_id, name) VALUES (226,'FZR 600N');
INSERT INTO model (brand_id, name) VALUES (226,'JOG 50');
INSERT INTO model (brand_id, name) VALUES (226,'JOG TEEN 50');
INSERT INTO model (brand_id, name) VALUES (226,'MIDNIGHT WARRIOR');
INSERT INTO model (brand_id, name) VALUES (226,'MT-01');
INSERT INTO model (brand_id, name) VALUES (226,'MT-03');
INSERT INTO model (brand_id, name) VALUES (226,'NEO AT 115');
INSERT INTO model (brand_id, name) VALUES (226,'NEO CVT 115');
INSERT INTO model (brand_id, name) VALUES (226,'RD 125');
INSERT INTO model (brand_id, name) VALUES (226,'RD 135');
INSERT INTO model (brand_id, name) VALUES (226,'RD 350');
INSERT INTO model (brand_id, name) VALUES (226,'RD 350 LC');
INSERT INTO model (brand_id, name) VALUES (226,'RD 350R');
INSERT INTO model (brand_id, name) VALUES (226,'RDZ 125');
INSERT INTO model (brand_id, name) VALUES (226,'RDZ 135');
INSERT INTO model (brand_id, name) VALUES (226,'ROAD STAR 1600');
INSERT INTO model (brand_id, name) VALUES (226,'ROYAL STAR 1300');
INSERT INTO model (brand_id, name) VALUES (226,'RX 125');
INSERT INTO model (brand_id, name) VALUES (226,'TDM 225');
INSERT INTO model (brand_id, name) VALUES (226,'TDM 850');
INSERT INTO model (brand_id, name) VALUES (226,'TDM 900');
INSERT INTO model (brand_id, name) VALUES (226,'TDR 180');
INSERT INTO model (brand_id, name) VALUES (226,'TMAX XP 500');
INSERT INTO model (brand_id, name) VALUES (226,'TRX 850');
INSERT INTO model (brand_id, name) VALUES (226,'TT 125');
INSERT INTO model (brand_id, name) VALUES (226,'TT-R 125E');
INSERT INTO model (brand_id, name) VALUES (226,'TT-R 125L');
INSERT INTO model (brand_id, name) VALUES (226,'TT-R 125LE');
INSERT INTO model (brand_id, name) VALUES (226,'TT-R 125LWE');
INSERT INTO model (brand_id, name) VALUES (226,'TT-R 230');
INSERT INTO model (brand_id, name) VALUES (226,'TX 650');
INSERT INTO model (brand_id, name) VALUES (226,'V MAX 1200');
INSERT INTO model (brand_id, name) VALUES (226,'V MAX 1800');
INSERT INTO model (brand_id, name) VALUES (226,'V STAR 1100');
INSERT INTO model (brand_id, name) VALUES (226,'V STAR 650');
INSERT INTO model (brand_id, name) VALUES (226,'V STAR 650 CLASSIC');
INSERT INTO model (brand_id, name) VALUES (226,'WR 200');
INSERT INTO model (brand_id, name) VALUES (226,'WR 250F');
INSERT INTO model (brand_id, name) VALUES (226,'WR 426F');
INSERT INTO model (brand_id, name) VALUES (226,'WR 450F');
INSERT INTO model (brand_id, name) VALUES (226,'XJ6 F');
INSERT INTO model (brand_id, name) VALUES (226,'XJ6 N');
INSERT INTO model (brand_id, name) VALUES (226,'XJR 1200');
INSERT INTO model (brand_id, name) VALUES (226,'XJR 1300');
INSERT INTO model (brand_id, name) VALUES (226,'XT 225');
INSERT INTO model (brand_id, name) VALUES (226,'XT 600 E');
INSERT INTO model (brand_id, name) VALUES (226,'XT 600Z TÉNÉRÉ');
INSERT INTO model (brand_id, name) VALUES (226,'XT 660 R');
INSERT INTO model (brand_id, name) VALUES (226,'XT1200Z SUPER TÉNÉRÉ');
INSERT INTO model (brand_id, name) VALUES (226,'XTZ 125 E');
INSERT INTO model (brand_id, name) VALUES (226,'XTZ 125 K');
INSERT INTO model (brand_id, name) VALUES (226,'XTZ 125 X/E');
INSERT INTO model (brand_id, name) VALUES (226,'XTZ 125 X/K');
INSERT INTO model (brand_id, name) VALUES (226,'XTZ 250 LANDER');
INSERT INTO model (brand_id, name) VALUES (226,'XTZ 250 TÉNÉRÉ');
INSERT INTO model (brand_id, name) VALUES (226,'XTZ 250 X');
INSERT INTO model (brand_id, name) VALUES (226,'XTZ 750S TENERE');
INSERT INTO model (brand_id, name) VALUES (226,'XV 1100 VIRAGO');
INSERT INTO model (brand_id, name) VALUES (226,'XV 250 VIRAGO');
INSERT INTO model (brand_id, name) VALUES (226,'XV 535S VIRAGO');
INSERT INTO model (brand_id, name) VALUES (226,'XV VIRAGO 750');
INSERT INTO model (brand_id, name) VALUES (226,'XVS 950 MIDNIGHT STAR');
INSERT INTO model (brand_id, name) VALUES (226,'YBR 125 E');
INSERT INTO model (brand_id, name) VALUES (226,'YBR 125 ED');
INSERT INTO model (brand_id, name) VALUES (226,'YBR 125 FACTOR E');
INSERT INTO model (brand_id, name) VALUES (226,'YBR 125 FACTOR ED');
INSERT INTO model (brand_id, name) VALUES (226,'YBR 125 FACTOR ED CENTENÁRIO');
INSERT INTO model (brand_id, name) VALUES (226,'YBR 125 FACTOR K');
INSERT INTO model (brand_id, name) VALUES (226,'YBR 125K');
INSERT INTO model (brand_id, name) VALUES (226,'YFM 125 GRIZZLY');
INSERT INTO model (brand_id, name) VALUES (226,'YFM 250 BIG BEAR');
INSERT INTO model (brand_id, name) VALUES (226,'YFM 250R');
INSERT INTO model (brand_id, name) VALUES (226,'YFM 350 GRIZZLY');
INSERT INTO model (brand_id, name) VALUES (226,'YFM 350R');
INSERT INTO model (brand_id, name) VALUES (226,'YFM 660 GRIZZLY');
INSERT INTO model (brand_id, name) VALUES (226,'YFM 660R RAPTOR');
INSERT INTO model (brand_id, name) VALUES (226,'YFM 700 GRIZZLY');
INSERT INTO model (brand_id, name) VALUES (226,'YFM 700R');
INSERT INTO model (brand_id, name) VALUES (226,'YFM 80R');
INSERT INTO model (brand_id, name) VALUES (226,'YFS 200 BLASTER');
INSERT INTO model (brand_id, name) VALUES (226,'YFZ 450');
INSERT INTO model (brand_id, name) VALUES (226,'YP 250 MAJESTY');
INSERT INTO model (brand_id, name) VALUES (226,'YZ 125');
INSERT INTO model (brand_id, name) VALUES (226,'YZ 250');
INSERT INTO model (brand_id, name) VALUES (226,'YZ 250F');
INSERT INTO model (brand_id, name) VALUES (226,'YZ 450F');
INSERT INTO model (brand_id, name) VALUES (226,'YZ 80');
INSERT INTO model (brand_id, name) VALUES (226,'YZ 85 LW');
INSERT INTO model (brand_id, name) VALUES (226,'YZF 1000 THUNDERACE');
INSERT INTO model (brand_id, name) VALUES (226,'YZF 450');
INSERT INTO model (brand_id, name) VALUES (226,'YZF 600 THUNDERCAT');
INSERT INTO model (brand_id, name) VALUES (226,'YZF 750');
INSERT INTO model (brand_id, name) VALUES (226,'YZF-R1');
INSERT INTO model (brand_id, name) VALUES (226,'YZF-R125');
INSERT INTO model (brand_id, name) VALUES (226,'YZF-R6');
 
INSERT INTO model (brand_id, name) VALUES (227,'YG200-9');

INSERT INTO model (brand_id, name) VALUES (228,'CHOPPER COBRA');

INSERT INTO model (brand_id, name) VALUES (229,'FOREST 150');
INSERT INTO model (brand_id, name) VALUES (229,'ZY 125 T5');
